### PR TITLE
refactoring(theme): Simplify exports

### PR DESCRIPTION
**Pull request by selbekk**
Remove more than half the code by using more modern syntax.

## 📝 Description

> Came across a unnecessarily bloated way of re-exporting default exports. This change simplifies it a bit.

## 💣 Is this a breaking change (Yes/No):

Nope.

## 📝 Additional Information

Totally understand if this is a stylistic choice, so if you don't want it, just close my PR, no feelings will be hurt.

### CODE REVIEW

**Comment by TimKolberger** [comment]
The new export syntax is great ✨ 
Currently it fails due the removed default export. Could you update the import of the theme components?

**Review by TimKolberger — CHANGES_REQUESTED** [review]
The new export syntax is great ✨
Currently it fails due the removed default export. Could you update the import of the theme components?

**Comment by selbekk** [comment]
Of course 😅 Thanks!

**Comment by selbekk** [comment]
Hm, not sure why the Release Snapshot fails, looks like there's an issue with my npm user or what not? Either way, the build passes now :)

**Pull request merged**
