### PR TITLE
docs(website): removed blog

### LINKED ISSUE #4488: Remove the blog section
### Subject

Blog

### Description

I think the blog section should be removed from the chakra-ui webpage since there is no content since November 13, 2020.
This seems like the project is stale if you are just looking at the blog.

### PR DESCRIPTION
**Pull request by MasterGordon**
Closes #4488

## 📝 Description

This PR removes the blog section because it is not maintained.

## 🚀 New behavior

No blog section on the webpage

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by MasterGordon** [comment]
I don't know why the Vercel build fails. On my machine I can run `next build` without issues.

**Comment by takethefake** [comment]
I would remove the blog after #4493 is merged

**Comment by takethefake** [comment]
Rebased it locally to the current `main`-branch and just works fine! +1 from my side.

**Review by takethefake — APPROVED** [review]

**Comment by TimKolberger** [comment]
Thank you for working on this @MasterGordon ✨ 
I just rebased and merged the changes into main.

**Pull request closed without merging**
