### PR TITLE
test: add tests for component packages

### PR DESCRIPTION
**Pull request by with-heart**
I've been working on adding tests for component packages. Wanted to open a PR to show existing progress, keep tabs on what's left, and get some feedback on testing some of the more complex components.

- [x] `Alert`
- [x] `Avatar` + `AvatarGroup`
- [x] `Breadcrumb`
- [x] `Button` + `ButtonGroup`
- [x] `CloseButton`
- [ ] `Descendant`
- [x] `Dialog`
- [x] `Drawer`
- [x] `Editable`
- [x] `FocusLock`
- [x] `FormControl`
- [x] `Icon`
- [x] `Image`
- [x] `Input`
- [ ] layout components (might do a separate PR for those)
- [x] `LiveRegion`
- [ ] `Menu`
- [x] `PinInput`
- [x] `Popover`
- [ ] `Popper`
- [ ] `Portal`
- [x] `Progress`
- [x] `Radio`
- [x] `Select`
- [x] `Slider`
- [x] `Spinner`
- [x] `Stat`
- [ ] `Switch`
- [ ] `Tabbable`
- [ ] `Tabs`
- [x] `Tag`
- [x] `Textarea`
- [ ] `Toast`
- [ ] `Tooltip`
- [ ] `Transition`
- [x] `VisuallyHidden`

### CODE REVIEW

**Comment by segunadebayo** [comment]
Amazing @with-heart! Let me know if you need any help.

Thank you for this!

**Comment by with-heart** [comment]
Glad I can contribute!

Should I open separate issues for things I'm noticing as I'm going through these? Not sure how you're tracking work for `dev-ts`.

**Comment by segunadebayo** [comment]
@with-heart. If you find any issues, let's chat here: https://discord.gg/4XhrCz

**Comment by segunadebayo** [comment]
You're the best @with-heart ❤️. Thank you so much for these testing efforts

**Pull request merged**
