### PR TITLE
docs(contributing): add details to "Steps to PR"

### PR DESCRIPTION
**Pull request by raulrpearson**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

I added some details to the "Steps to PR" section that tripped me up on my previous (first) PR.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jvmazagao — APPROVED** [review]

**Review by TimKolberger — APPROVED** [review]

**Comment by with-heart** [comment]
So I know that it already existed before you touched this, but now that I'm re-reading it, I think I'd vote to remove everything related to the `changeset` command from this doc. `changeset` was added as a way for maintainers to manage the content of our generated changelogs and isn't meant to be a part of the process for individual contributors.

@chakra-ui/react-team: Thoughts on this?

**Comment by jmiazga** [comment]
@with-heart What would the process look like if we had to generate the changesets? When would they be generated?

**Comment by TimKolberger** [comment]
What would be the benefit if just the maintains would write a changelog entry?
If a changeset is already filled out, we have less maintaining to do. 

I would love to see an example changeset in the contribution guide to show contributors what wording should be used in the changeset.

**Comment by segunadebayo** [comment]
I see what you mean @with-heart but I'd say we should allow contributors to generate changesets to document their changes.

It'll save us time and prevent us from having to read the code changes to manually add changesets.

@jmiazga and @TimKolberger, changeset-bot usually informs us when a PR doesn't include a changeset and we can click a button to add the changeset for that PR.

It's a time saver if the contributor adds the changeset, but we can also do this. I'd vote for keeping it as is and adding to the docs (perhaps as a recommended but optional step)

**Pull request merged**
