### PR TITLE
fix(drawer): close button styles

### PR DESCRIPTION
**Pull request by TimKolberger**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix

## What is the current behavior?

Postition of Close Button in a Drawer has incorrect position.

## What is the new behavior?

- Postion is fixed
- Additional styles are applied correctly

## Does this introduce a breaking change?

- [x] No

## Other information

@dodas is the original author, I just created a PR for those changes

### CODE REVIEW

**Comment by dodas** [comment]
Thanks and sorry for a mess!

**Comment by TimKolberger** [comment]
No worries @dodas! 

The code looks good to me. [The Close Button is at the correct position in the Drawer](https://chakra-ui-8jl30qfvz.vercel.app/docs/overlay/drawer) 👍

**Comment by with-heart** [comment]
Merged the changesets and updated the message a bit!

**Review by with-heart — APPROVED** [review]

**Comment by rserafim** [comment]
it was not clear to me. Will it be fixed in any version? Tks

**Pull request merged**
