### PR TITLE
fix(icons): set viewBox on DragHandle icon, restore default dimensions

### PR DESCRIPTION
**Pull request by dustinlarimer**
This PR sets a default `viewBox` value for `DragHandleIcon`, restoring the proper dimensions for this particular SVG element.

**Before**

Screen Shot 2020-07-22 at 9 54 11 AM

**After**

Screen Shot 2020-07-22 at 9 56 38 AM

### CODE REVIEW

**Comment by dustinlarimer** [comment]
This failed status check seems unrelated to the updates, but I also encountered this locally when trying to get the project to build properly:

```bash
##[error]@chakra-ui/tabs: [build:types] src/tabs.tsx(87,39): error TS2322: Type 'Ref<any>' is not assignable to type 'RefObject<HTMLElement> | undefined'.
```

Any insight or guidance on how to resolve this?

Thanks!

**Comment by dustinlarimer** [comment]
Perhaps related to https://github.com/chakra-ui/chakra-ui/commit/64205e12081366b5b694215f5fe1a4aa4bd0b779?

**Comment by segunadebayo** [comment]
Thank you for this PR, @dustinlarimer.

Can you rebase with `develop`, I've just resolved the issue.

**Comment by dustinlarimer** [comment]
Excellent - thank you, @segunadebayo!

**Comment by with-heart** [comment]
Aw, I'm sorry @dustinlarimer! I merged #1392 earlier today which fixed this same issue. Didn't realize you already had this open.

**Comment by dustinlarimer** [comment]
All good @with-heart, happy it got fixed up just the same 🚀

**Pull request closed without merging**
