### PR TITLE
fix: resolve yarn v2 pnp issues

### PR DESCRIPTION
**Pull request by gordlea**
I was trying out the yarn v2 release candidate, and ran across issues using chakra-ui with a project of mine.

They are all dependency/peerDependency issues. Before my updates, I was getting the following warnings running yarn:

```
❯ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @react-spring/core@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@^16.8.0 requested by use-memo-one@npm:1.1.1
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by @react-spring/addons@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide konva@>=2.6 requested by @react-spring/konva@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by @react-spring/konva@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react-konva@>=16.8 requested by @react-spring/konva@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by @react-spring/native@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react-native@>=0.58 requested by @react-spring/native@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by @react-spring/three@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react-three-fiber@>=2.0 requested by @react-spring/three@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide three@>=0.104 requested by @react-spring/three@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by @react-spring/web@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react-dom@>=16.8 requested by @react-spring/web@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by @react-spring/zdog@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react-dom@>=16.8 requested by @react-spring/zdog@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react-zdog@>=1.0 requested by @react-spring/zdog@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide zdog@>=1.0 requested by @react-spring/zdog@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ @reach/alert@npm:0.1.5 [6511f] doesn't provide prop-types@^15.6.2 requested by @reach/component-component@npm:0.1.3
```

And the following breakages when running webpack build (edited for brevity, many similar errors removed, full log available on request):
```
ERROR in /path/to/my/project/.yarn/cache/@react-spring-animated-npm-9.0.0-canary.809.3.a66b280-d1ff118115.zip/node_modules/@react-spring/animated/index.js
Module not found: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: react (via "react")
Required by: @react-spring/animated@npm:9.0.0-canary.809.3.a66b280 (via /path/to/my/project/.yarn/cache/@react-spring-animated-npm-9.0.0-canary.809.3.a66b280-d1ff118115.zip/node_modules/@react-spring/animated/index.js)

 @ /path/to/my/project/.yarn/cache/@react-spring-animated-npm-9.0.0-canary.809.3.a66b280-d1ff118115.zip/node_modules/@react-spring/animated/index.js 6:0-50 518:45-55 519:22-28 545:9-14
 @ /path/to/my/project/.yarn/virtual/@react-spring-web-virtual-a428cfb2f8/0/cache/@react-spring-web-npm-9.0.0-canary.809.3.a66b280-77c9cd96ed.zip/node_modules/@react-spring/web/index.js
 @ /path/to/my/project/.yarn/cache/react-spring-npm-9.0.0-canary.809.3.a66b280-79383e0207.zip/node_modules/react-spring/web.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/Message.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/ToastManager.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/Toast.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/index.js
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/Toast/index.js
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/index.js
 @ ./src/main.js

ERROR in /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/CSSReset/index.js
Module not found: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: @babel/runtime (via "@babel/runtime/helpers/taggedTemplateLiteralLoose")
Required by: @chakra-ui/core@virtual:130c84d57260c8520bce27d015c801af805a16f78bada4ba941fcd9c66a981b825c20990855ddd8937c212390e7c2b7a46bd46b54ac36704a66a2f225c2b7ecc#npm:0.3.2 (via /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/CSSReset/index.js)

 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/CSSReset/index.js 1:0-92 4:13-40
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/index.js
 @ ./src/main.js


ERROR in /path/to/my/project/.yarn/virtual/@reach-component-component-virtual-1b212e295a/0/cache/@reach-component-component-npm-0.1.3-94c20ffc6f.zip/node_modules/@reach/component-component/es/index.js
Module not found: Error: A package is trying to access a peer dependency that should be provided by its direct ancestor but isn't

Required package: prop-types (via "prop-types")
Required by: @reach/component-component@virtual:ab71b639f6610e4dc9442d7d3ed938120a8fba4af3488976f3a0f33fa2cc526a3a6f2f25c2ca32df041eb9f3cdf7ccc909527bbee1f5387e4872268da091e058#npm:0.1.3 (via /path/to/my/project/.yarn/virtual/@reach-component-component-virtual-1b212e295a/0/cache/@reach-component-component-npm-0.1.3-94c20ffc6f.zip/node_modules/@reach/component-component/es/index.js)

 @ /path/to/my/project/.yarn/virtual/@reach-component-component-virtual-1b212e295a/0/cache/@reach-component-component-npm-0.1.3-94c20ffc6f.zip/node_modules/@reach/component-component/es/index.js 10:0-59 132:16-22 133:19-23 134:8-14 135:11-15 136:12-16 137:13-17 138:15-19 139:27-31 140:16-20 141:10-14 142:12-21 142:23-27 142:29-33
 @ /path/to/my/project/.yarn/virtual/@reach-alert-virtual-ab71b639f6/0/cache/@reach-alert-npm-0.1.5-9ba9a0e66d.zip/node_modules/@reach/alert/es/index.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/Message.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/ToastManager.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/Toast.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/index.js
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/Toast/index.js
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/index.js
 @ ./src/main.js


ERROR in /path/to/my/project/.yarn/virtual/use-memo-one-virtual-1ffc48c826/0/cache/use-memo-one-npm-1.1.1-41d1dc2ef9.zip/node_modules/use-memo-one/dist/use-memo-one.esm.js
Module not found: Error: A package is trying to access a peer dependency that should be provided by its direct ancestor but isn't

Required package: react (via "react")
Required by: use-memo-one@virtual:10b1f2df4f6943e601f19c7c4aebc6a0fd5a80a4dfa5d837722ffec27325d7aab9aa9b534665664d80ec402ec29c4bedd854760dd6300abba3efb39daa9d4b09#npm:1.1.1 (via /path/to/my/project/.yarn/virtual/use-memo-one-virtual-1ffc48c826/0/cache/use-memo-one-npm-1.1.1-41d1dc2ef9.zip/node_modules/use-memo-one/dist/use-memo-one.esm.js)

 @ /path/to/my/project/.yarn/virtual/use-memo-one-virtual-1ffc48c826/0/cache/use-memo-one-npm-1.1.1-41d1dc2ef9.zip/node_modules/use-memo-one/dist/use-memo-one.esm.js 1:0-52 18:16-24 24:18-24 30:2-11
 @ /path/to/my/project/.yarn/unplugged/@react-spring-core-npm-9.0.0-canary.809.3.a66b280-10b1f2df4f/node_modules/@react-spring/core/index.js
 @ /path/to/my/project/.yarn/virtual/@react-spring-web-virtual-a428cfb2f8/0/cache/@react-spring-web-npm-9.0.0-canary.809.3.a66b280-77c9cd96ed.zip/node_modules/@react-spring/web/index.js
 @ /path/to/my/project/.yarn/cache/react-spring-npm-9.0.0-canary.809.3.a66b280-79383e0207.zip/node_modules/react-spring/web.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/Message.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/ToastManager.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/Toast.js
 @ /path/to/my/project/.yarn/virtual/toasted-notes-virtual-6511f0e024/0/cache/toasted-notes-npm-2.1.6-d78ea7a248.zip/node_modules/toasted-notes/lib/index.js
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/Toast/index.js
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-36cb862b0f/0/cache/@chakra-ui-core-npm-0.3.2-5c3a781b78.zip/node_modules/@chakra-ui/core/dist/es/index.js
 @ ./src/main.js
```

The changes in this PR resolve most of the issues above, by adding some missing deps and updating toasted-notes to version 3.0.0.

The remaining issue has to do with @reach/alert, which is brought in by toasted-notes:

```
@reach/alert@npm:0.1.5 [37363] doesn't provide prop-types@^15.6.2 requested by @reach/component-component@npm:0.1.3
```

Yarn pnp is strict about peerDeps being provided, and so this breaks the build. Since I don't use chakra-ui's Toast notifications, I was able to work around the issue using the webpack null-loader:
```
    module: {
        rules: [{
            // Test for a polyfill (or any file) and it won't be included in your
            // bundle
            test: /chakra-ui\/dist\/es\/Toast\/index.js/,
            use: 'null-loader',
          },
       ...
    } 

```

There will have to be a fix in the @reach/alert project to resolve the actual issue.

### CODE REVIEW

**Comment by gordlea** [comment]
I'm not sure why the storybook build is failing, it's working locally for me.

**Comment by segunadebayo** [comment]
@gordlea, same here. I'm not sure why the Storybook build is failing as well. Been trying to fix it for a couple of days now.

As regards this issue, I see you've added `@styled-system/core` to the dependencies. I thought it was already a dependency in `styled-system`.

**Comment by gordlea** [comment]
@segunadebayo I did add it as a dependency, without it I was getting the following error on build:

```
ERROR in /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-d568757506/2/chakra-ui/packages/chakra-ui/dist/es/Input/styles.js
Module not found: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: @styled-system/core (via "@styled-system/core")
Required by: @chakra-ui/core@virtual:130c84d57260c8520bce27d015c801af805a16f78bada4ba941fcd9c66a981b825c20990855ddd8937c212390e7c2b7a46bd46b54ac36704a66a2f225c2b7ecc#portal:../../../chakra-ui/packages/chakra-ui?locator=%40gordlea%2Fbbq-web%40workspace%3Apackages%2Fweb (via /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-d568757506/2/chakra-ui/packages/chakra-ui/dist/es/Input/styles.js)

 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-d568757506/2/chakra-ui/packages/chakra-ui/dist/es/Input/styles.js 39:0-42 65:26-29 68:26-29 114:26-29 116:26-29 144:26-29 146:26-29
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-d568757506/2/chakra-ui/packages/chakra-ui/dist/es/Input/index.js
 @ /path/to/my/project/.yarn/virtual/@chakra-ui-core-virtual-d568757506/2/chakra-ui/packages/chakra-ui/dist/es/index.js
 @ ./src/main.js
```

Basically yarn pnp is stricter on dependencies, it won't let you import a dependency that isn't explicitly imported.

> This error simply means that the specified package is requiring something without explicitly declaring it in its dependencies. Since this behavior is unsafe and relies on the hoisting being done a certain way, Plug’n’Play doesn’t allow it.

See: 
* https://yarnpkg.com/en/docs/pnp/troubleshooting#toc-is-trying-to-require-without-it-being-listed-in-its-dependencies
* https://next.yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-

**Comment by gordlea** [comment]
BTW: It looks like the fix to @reach/alert has been merged into master, just waiting for them to release: https://github.com/reach/reach-ui/pull/277

**Comment by segunadebayo** [comment]
Ah. I see what you mean. I've updated the Input component to import from `styled-system` instead of `@styled-system/core`. It works, so we might not need to add `@styled-system/core` as a dependency.

As for @reach/alert, the error is coming from the library `toasted-notes`. I hope they release it soon so I can notify the library author to upgrade the package. I believe that should fix it.

**Comment by gordlea** [comment]
Nice, I'll update the pr from master and try it out.

**Comment by gordlea** [comment]
@segunadebayo Looks like that worked, I was able to remove it. Pr updated. Would you rather I rebase it into a single commit? Or do you squash and merge?

**Comment by segunadebayo** [comment]
Great! Kindly rebase into a single commit @gordlea

**Comment by gordlea** [comment]
Rebased as requested

**Pull request merged**
