### PR TITLE
feat(theme): Add XXL breakpoint and container size to default theme.

### PR DESCRIPTION
**Pull request by DaniHv**
#About PR - #2471 

This PR add a new breakpoint and container size maxW (XXL) with 90rem/1440px.

- [ X ] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

- [X] Feature
- [X] Documentation content changes

## What is the current behavior?

Fixes: https://github.com/chakra-ui/chakra-ui/issues/2471

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by segunadebayo** [comment]
Thanks for this @DaniHv. I'd recommend changing the name to `2xl` instead to `xl` to keep it consistent with the naming of the fontSizes in the theme.

**Comment by with-heart** [comment]
Not sure what happened exactly but it looks like the commits have gone a little haywire here

**Comment by with-heart** [comment]
But it's not unfixable! I'd still love to merge this @DaniHv. Mind if I help sort out the commits here?

**Comment by DaniHv** [comment]
> But it's not unfixable! I'd still love to merge this @DaniHv. Mind if I help sort out the commits here?

Sure @with-heart ! I still haven't given up haha, i'm trying to do it in a cleaner way and with the suggested name '2xl' by @segunadebayo Segun. (Additionals things (but easy) to do because breakpoints actually use dot '.' to access elements (breakpoints.md) instead of ['md'] required for 2xl, 3...)

But... i'm having some troubles trying to run 'yarn test' tests in my pc that doesn't happen here, don't know exactly why, it's my first time with monorepos. I'm using Yarn 1.23 (with berry is worse). Among other things, a lot of 'Cannot find module' in almost every package (obviously after installing everything with yarn, yarn install and even yarn prestart). Trying in Windows, and WSL and nothing.

Probably it's a stupid thing that i didn't learn before, but i really want to contribute and this is not the only thing I have planned

**Comment by ljosberinn** [comment]
on the top level of the repo, try `rm -rf node_modules && rm yarn.lock && yarn prestart`, I'm using that exclusively :)

**Comment by DaniHv** [comment]
> on the top level of the repo, try `rm -rf node_modules && rm yarn.lock && yarn prestart`, I'm using that exclusively :)
> 
> Edit: given you forked the repo before the v1 release, unluckily, I'd start anew though, sorry for the inconvenience!

I did it, but i still have same problems. I also tried with Ubuntu Server vps and clean node v14.15.0/npm/yarn v1.22.5 (same as GitHub tests).

screenshot: https://prnt.sc/vj6x3z

**Pull request closed without merging**
