### PR TITLE
feat(popover): PopoverAnchor

### LINKED ISSUE #4733: feat(popover): manual trigger mode
Hello Chakra folks!

### Problem Statement/Justification

I have a use case where I need to have a `Popover` where neither clicking nor hovering on the trigger should toggle the visibility of the popover.
Similar to the [Controlled Usage example](https://chakra-ui.com/docs/overlay/popover#controlled-usage), however I want the `Popover Target` button to not close the popover.
In my case the `PopoverTrigger` children is an input and I want to be able to click inside it without closing the popover.

My current workaround:
```tsx
<Popover
    isOpen={isOpen}
    onClose={onClose}
    closeOnBlur={false}
    // Passing anything else than `click` or `hover` works, however TS types do not accept it.
    trigger={"manual" as any}
>
    ...
</Popover>
```

### Proposed Solution or API

Add a `manual` mode for `trigger`. Or should it be called `none` instead?

It seems like just adding this value to the possible `TRIGGER` values makes this work, since Chakra doesn't bind any event listeners in that case.

_____
Thanks!

### PR DESCRIPTION
**Pull request by dodas**
## 📝 Description

Follow up on https://github.com/chakra-ui/chakra-ui/pull/4734
Closes #4733

Demo: an Input with a popover

https://user-images.githubusercontent.com/14360171/141017574-e91c3e52-88ff-4229-a2d1-a42731c9a50d.mov

### CODE REVIEW

**Comment by dodas** [comment]
I feel like the code around `anchorRef`/`maybeReferenceRef` is a bit unreadable. However, I think it's quite concise and does exactly what we need.

Any suggestions on how we can improve it are welcome!

**Comment by dodas** [comment]
@segunadebayo
did you have a chance to look?
any feedback is welcome!

**Review by segunadebayo — APPROVED** [review]
I think this looks good @dodas. Great work 👌

Please add some documentation around this feature, and I'll get it merged.

**Comment by bielas** [comment]
We would like to build simple autocomplete component with an Input element as a popover trigger. Trigger should happen on input click. When popover opens we should be able to type our autocomplete text without focusing on input once again - on popover open, focus should stay on input which at the same time is a trigger. The solution we took is to put initialFocusRef on the input element. However it creates one problem - popover doesnt close on clicking outside the whole component but on clicking again on the trigger - input element. How to achieve that, how to fix that problem?

**Pull request merged**
