### PR TITLE
feat(website): adding side nav with scrollspy

### LINKED ISSUE #3901: [Docs]: Add section navigation on the right side for docs
First of all, Amazing library. Probably best React component library I've seen these days. Great work 👏🏽 

# 🚀 Feature request

Please add a right side navigation in docs for sub-sections of a page.

## 🧱 Problem Statement / Justification

If I have to find a section in a page, I have to keep scrolling up/down searching for a section. For example, In [https://chakra-ui.com/docs/form/button](https://chakra-ui.com/docs/form/button) page, navigation will be easier if it shows links on the right side for Usage, Button Sizes, .... and other sections. It'll help quickly go back to what I'm looking for. Something like [https://ant.design/components/button](https://ant.design/components/button/) has

## ✅ Proposed solution or API

I believe all sections on each doc page already have `#section-name` which we can use in a `href` and build a nav list with links. Extra features may include a scrollspy.

Thank you

### PR DESCRIPTION
**Pull request by jamesaucode**
Closes #3901

## 📝 Description

This adds a side navigation bar to the doc site. The `<SectionNavigation>` component will list the <a> links that links to all the `<h2>`s on the page. It also has a scrollspy that indicates where the user is at on the page.

## ⛳️ Current behavior (updates)

There's no side navigation bar in the current doc site.

## 🚀 New behavior

There will be a side navigation for users to jump between different section of a page

Here's a gif for a short demo
recording

## 💣 Is this a breaking change (Yes/No):

No.

## 📝 Additional Information

First time contributor to Chakra :smile: Please let me know if I missed anything, or if there are any design decisions that needs to be changed.

### CODE REVIEW

**Comment by jamesaucode** [comment]
Seems like there's a TS error, will fix it tomorrow

**Review by with-heart — APPROVED** [review]
This looks great! The `useScrollSpy` hook is awesome.

**Comment by jamesaucode** [comment]
@with-heart Thank you! Looking at the Vercel preview it seems like mobile is looking a little weird, I will push another change in a moment to fix it

**Comment by segunadebayo** [comment]
Great work @jamesaucode! That code looks elegant to me.

I'll help tweak the design a little bit and merge after you fix the mobile.

**Comment by jamesaucode** [comment]
Thank you @segunadebayo , just got off work, will try to get a fix up for mobile now

**Comment by jamesaucode** [comment]
Did some more manual visual testing, besides the mobile view ,I saw some overlap of text on tablet - smaller laptop screen sizes so I got another commit to deal with that too. My CSS-fu definitely need some work ... :thinking:

**Comment by jamesaucode** [comment]
This last commit should solve the problem, without restricting the minWidth it's allowing text in the flex container to grow beyond its width.

**Pull request merged**
