### PR TITLE
Feat/gh3911 toast loading status

### PR DESCRIPTION
**Pull request by jatin33**
Closes #  https://github.com/chakra-ui/chakra-ui/issues/3911

## 📝 Description

> This PR adds a new hook to toast package which allows for async/loading toasts

## ⛳️ Current behavior (updates)

> There is no support for async/loading toasts

## 🚀 New behavior

> This PR adds a new hook to toast package which allows for async/loading toasts

### CODE REVIEW

**Comment by jatin33** [comment]
@with-heart @segunadebayo please give feedback

**Comment by takethefake** [comment]
@jatin33 checked your PR and it looks good to me in general. It would be nice if you could adjust your commit so that only relevant files are changed.

**Comment by segunadebayo** [comment]
This looks interesting @jatin33. I'd like to tweak the API you created a bit.

`useAsyncToast` seems to deviate from the API of `useToast` and I want to keep them consistent. Ideally, this loading functionality should be embedded in `useToast` itself so we don't increase the API surface.

What I have in mind is something similar to: https://react-hot-toast.com/docs/toast#promise where the loading toast is assumed to be a promise that can either resolve or reject. When it resolves we want to change the loading status to `success` and when it fails, we want to change it to `error`.

```jsx
const toast = useToast()

// 1. I'll implement the "loading" status in the toast to have no timeout duration `duration: null`
toast({ status: "loading", title: "...", description: "..." })

// 2. I'll implement a promise method on toast to allow changing the toast options when the promise resolves or rejects.
toast.promise(promise, { success: {}, error: {}, loading: {}  } )
```

This change will remove the need for `useAsyncToast` and provide a good base for our upcoming updates to the toast API.

**Comment by jatin33** [comment]
Will soon modify this, thanks for the feedback!

**Comment by cschroeter** [comment]
Unfortunately, there have been no recent changes to this PR. To have a better overview of open PR, I have to close this one.

Please feel free to open it again if needed.

**Comment by marek-sed** [comment]
Hi we have a requirement for toast with loading status, can I try to finish this PR?

**Comment by anubra266** [comment]
@marek-sed feel free to.

**Comment by jatin33** [comment]
Sorry guys, been a little busy, let me give this a shot this weekend else @marek-sed can pickup

**Comment by marek-sed** [comment]
@jatin33 so how is it going, should I take over?

**Pull request closed without merging**
