### PR TITLE
fix(avatar): add loading prop for avatar

### PR DESCRIPTION
**Pull request by Zaynex**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Fixes: [ISSUE NUMBER]

## What is the new behavior?

- Suport avatar image loading strategy

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
see #2150

### CODE REVIEW

**Comment by ljosberinn** [comment]
thank you - would you mind using `import type { ImageProps } from '@chakra-ui/image'` and use `ImageProps['image']` instead? That way, they'll stay in sync.

**Comment by Zaynex** [comment]
What about  `borderRadius` and `getInitials`? It seems almost the same but need extends.

**Comment by ljosberinn** [comment]
In all honesty, since  the component is internal only anyways, we might aswell just extend it like you proposed, good idea!

**Comment by ljosberinn** [comment]
fixes #2150

**Comment by Zaynex** [comment]
done

**Comment by ljosberinn** [comment]
LGTM

**Pull request merged**
