### PR TITLE
chore: add pull request template for contributors

### LINKED ISSUE #1739: Create pull request template
A pull request template allows us to explicitly define our expectations for contributors when creating a pull request.

Our template should provide contributors with prompts for information to fill out relating to the pull request. The prompts should encourage users to share information about their PR like what problem(s) it is attempting to address, what steps they took to address the problem(s), to link to any related issues. This information will make it easier for maintainers to quickly understand what the PR is trying to achieve in order to provide a thorough code review.

We could also consider having a basic checklist for the contributor to check off, like if they added tests and documentation (if applicable), to help set expectations around what should be included in a PR.

See https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository for documentation on how to create the template.

See https://github.com/devspace/awesome-github-templates for examples and inspiration.

### PR DESCRIPTION
**Pull request by vickywane**
This closes #1739 as opened by @with-heart .

This is a pull request template crafted using this [template](https://github.com/ionic-team/ionic-framework/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

### CODE REVIEW

**Comment by with-heart** [comment]
@vickywane This is awesome! Thank you!

**Comment by with-heart** [comment]
I'll get this merged today

**Comment by vickywane** [comment]
Thank you !!

**Comment by with-heart** [comment]
Made a few small updates! Once this passes we should be good to go on merging :)

**Pull request merged**
