### PR TITLE
[Checkbox] Add 'isReadOnly' attribute

### PR DESCRIPTION
**Pull request by Rahmon**
I've added the isReadOnly prop to Checkbox component.

#52

### CODE REVIEW

**Comment by segunadebayo** [comment]
Thanks for attempting to fix this @Rahmon.

I'm trying to fix the Storybook deployment issue but I wanted to ask, based on your changes, does it prevent the user from changing the checked state of the Checkbox?

It seems likes you only applied a visual change. Ideally, we want to prevent the "onChange" from firing if the `isReadOnly` prop is present. Or did you account for this already?

**Comment by Rahmon** [comment]
@segunadebayo 

Yes, I've applied only a visual change because the specification I've found in MDN Web Docs about [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#readonly) attribute say that:

> Note that since the value of the checkbox is not exposed by the browser to the user this attribute **only changes the appearance** of the checkbox, typically by displaying with a gray rather than black outine and  gray rather than white background when not checked.  However this attribute does not apply to the checked state of the attribute, which can **still be altered by the user**.  If you also want to prevent the user from changing the checked state of the element you must also specify the disabled attribute.

Anyway, I can update to prevent the "onChange" firing if this is the expected behavior.

**Comment by segunadebayo** [comment]
Hi @Rahmon, I see what you mean and this is a controversial issue.

My thought will be that when users pass `isReadOnly`, they expect that the checkbox should be able allowed to change state. I understand native HTML doesn't do it this way but we could account for this.

Let's prevent the `onChange` from firing. Thank you for working on this.

**Comment by Rahmon** [comment]
Ok @segunadebayo. I'll do that.

**Comment by segunadebayo** [comment]
Hi @Rahmon, I'd like to merge your work. 

Let me know when you can finish this. Thanks

**Comment by Rahmon** [comment]
I'm thinking about prevent from firing, can I just set disabled as true? So when isReadOnly is true the input will be readonly and disabled.

**Comment by segunadebayo** [comment]
> @segunadebayo
> 
> I'm thinking about prevent from firing, can I just set disabled as true? So when isReadOnly is true the input will be readonly and disabled.

I'm not sure but if we mimic the behavior of  `<input type="text">`, when it has `readonly` set to `true`, the input doesn't look disabled, it looks normal but you just can't change the text.

In a similar way, the checkbox will look normal but you can't toggle it.

**Comment by Rahmon** [comment]
Hi @segunadebayo. I've finished. Could you review it?

**Pull request merged**
