### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by tony**

### CODE REVIEW

**Comment by with-heart** [comment]
Hi @tony! (Nice username!)

Could you please update your commit message(s) to fit the [Conventional Commits specification](https://www.conventionalcommits.org/)? 

We use this specification to automatically generate our `CHANGELOG`, so it's important that commits follow the spec.

Thank you!

**Comment by tony** [comment]
@with-heart Hi there!  Hope you're doing well

Any better now? (First time trying conventional commits!)

**Comment by with-heart** [comment]
@tony That's perfect! Thank you so much :)

**Comment by with-heart** [comment]
@all-contributors please add @tony for docs

**Pull request merged**
