### PR TITLE
Uses `keyof JSX.IntrinsicElements` for 'As' type used in PropsOf

### LINKED ISSUE #2294: TypeScript build error in rc.{3-5}
# Bug report

## Describe the bug
Using TypeScript with strict mode on, this internal error comes up.

```
node_modules/@chakra-ui/system/dist/types/forward-ref.d.ts:10:186 - error TS2344: Type 'T' does not satisfy the constraint '"symbol" | "object" | "button" | "meter" | "textarea" | "style" | "progress" | "text" | "ruby" | "table" | "small" | "sub" | "circle" | "embed" | "pre" | "caption" | "menu" | "menuitem" | ... 158 more ... | (new (props: any) => Component<...>)'.
  Type 'As' is not assignable to type '"symbol" | "object" | "button" | "meter" | "textarea" | "style" | "progress" | "text" | "ruby" | "table" | "small" | "sub" | "circle" | "embed" | "pre" | "caption" | "menu" | "menuitem" | ... 158 more ... | (new (props: any) => Component<...>)'.
    Type 'string' is not assignable to type '"symbol" | "object" | "button" | "meter" | "textarea" | "style" | "progress" | "text" | "ruby" | "table" | "small" | "sub" | "circle" | "embed" | "pre" | "caption" | "menu" | "menuitem" | ... 158 more ... | (new (props: any) => Component<...>)'.
      Type 'T' is not assignable to type '"view"'.
        Type 'As' is not assignable to type '"view"'.
          Type 'string' is not assignable to type '"view"'.

10 declare type PropsOf<T extends As> = T extends React.ComponentClass<infer P> ? React.PropsWithoutRef<P> & React.RefAttributes<InstanceType<T>> : React.PropsWithRef<React.ComponentProps<T>>;
```

### PR DESCRIPTION
**Pull request by joelgallant**
Fixes #2294

### CODE REVIEW

**Comment by joelgallant** [comment]
Test failure looks unrelated?

**Comment by ljosberinn** [comment]
Yeah I'm afraid you branched off develop right before I pushed the updated snapshots 👀 I'll try locally real quick

**Comment by ljosberinn** [comment]
thanks, works just nice!

**Comment by ljosberinn** [comment]
@allcontributors please add @joelgallant for bug

**Pull request merged**
