### PR TITLE
docs: guide for nextjs with custom font files

### PR DESCRIPTION
**Pull request by notbrett**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

This PR adds a short guide for adding font files to Chakra's default theme for apps running on Next.js. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ljosberinn** [comment]
nice work, thank you, reading through it right now :)

could you test whether you have 2 `<Global />` components showing up in the react devtools? I have a feeling the internals of `Global` are not clever enough to only render those styles once. we might be able to adapt the api of `ChakraProvider` for that, just like with `portalZIndex` and `resetCSS`. if this is indeed the case, what do you think of `<ChakraProvider resetCSS theme={theme} globalStyles={myVariable}>`?

**Comment by ljosberinn** [comment]
Also, I think it's worth mentioning this upcoming optimization for google fonts: https://twitter.com/wongmjane/status/1293076852190220288

**Comment by notbrett** [comment]
The optimization stuff is confusing to me. I decided to remove the Google Fonts bit and keep the guide focused on using font files in Next.js.

**Comment by notbrett** [comment]
I'm not sure about 2 `<Global />` components in react-devtools. Here is what I'm seeing:

Screen Shot 2020-09-02 at 5 58 07 PM

The first `<GlobalStyle>` contains the colorMode stuff. The second `render` has the @font-face stuff. I'm on Safari, so I'm using the funky NPM react-devtools (which I've only gotten to work for this!).

**Comment by notbrett** [comment]
A `globalStyles` prop on the `<ChakraProvider>` seems a better choice that a child `<Global>` component. However, I wonder if there is a way to integrate it into the theme and not as a separate prop/file. In my mind, anything happening globally is conceptually part of the `theme` declarations. I'm not sure what the pros and cons would be. Having a `globalStyles` prop might be the easiest first step. As far as I can tell, even as it is now is pretty fast.

**Comment by ljosberinn** [comment]
Didn't see you were using `Global`, not `GlobalStyle`, thats directly the emotion instance and that one is clever enough to merge actually.

I'm a bit conflicted right now though. Stumbled across [this](https://github.com/chakra-ui/chakra-ui/blob/develop/website/pages/_app.tsx#L30) implementation in the chakra docs itself.

Wouldn't this solve your initial issue anyways? 😅

**Comment by segunadebayo** [comment]
Hi @ljosberinn, I think it's fine to go with this approach as it helps other non-Nextjs users as well.

**Pull request merged**
