### PR TITLE
fix: lightMode flash issue

### PR DESCRIPTION
**Pull request by KristianRykkje**
Closes #  I couldn't find this issue.

## 📝 Description

> color-mode-script now sets the classname (light/dark) on the body.

## ⛳️ Current behavior (updates)

> When reloading the page after changed to dark mode it flashes light mode.
https://chakra-ui.com/docs/features/color-mode
image

## 🚀 New behavior

> Now the className (dark/light) should be set in the script before the "content".

## 💣 Is this a breaking change (Yes/No):
No

## 📝 Additional Information
This is my first PR to a open source project and would love some feedback on the way I made changes and maybe on some testing.

### CODE REVIEW

**Comment by KristianRykkje** [comment]
What I tried didn't work in the vercel build. Trying something else

**Comment by KristianRykkje** [comment]
With the changes I made chakra now correctly has the right className on the <body>. However the colors are still wrong... Are the colors not decided on the body className? If not, how are the colors decided?

**Comment by segunadebayo** [comment]
Hi @KristianRykkje,

At the moment, the components use javascript to listen to detect the color mode and change their styles accordingly. This is a limitation we had in mind to solve.

With your update, we'll need to update all component styles to rely on the `body` className `chakra-ui-dark` and change their style which better and in alignment with good'ol css.

**Comment by KristianRykkje** [comment]
sure @segunadebayo I'll give it a go this week

**Review by weishiji — APPROVED** [review]

**Comment by cschroeter** [comment]
Unfortunately, there has been no recent activity on this PR. To get a better overview of open PRs, I will close this one.

Please feel free to open it again if needed.

Thanks for supporting Chakra UI & Happy hacking ✌️

**Pull request closed without merging**
