### PR TITLE
fix(env): render span for env detection in portal

### LINKED ISSUE #6374: EnvironmentProvider appends a span to DOM which breaks some unit tests
### Description

I've noticed that EnvironmentProvider appends an empty span to the document which in my case breaks some unit tests that check if specified components do NOT render any elements. I'm using react-testing-library.

### Link to Reproduction

https://codesandbox.io/s/chakraprovider-empty-span-issue-qbmbdw

### Steps to reproduce

Visible in any case when ChakraProvider is being used.

### Chakra UI Version

2.2.4

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

It was already mentioned https://github.com/chakra-ui/chakra-ui/issues/5855#issuecomment-1095400843.

In my case, when using RTL to unit test a component, with following test:
```
    const { container } = customRender(<ComponentThatShouldNotRenderAnything />);

    expect(container).toBeEmptyDOMElement();
```

and setup like:
```
const TestProviders = ({ children }: { children: React.ReactNode }) => {
  return (
      <ChakraProvider theme={theme}>{children}</ChakraProvider>
  );
};

const customRender = (
  ui: React.ReactElement,
  options?: RenderOptions,
): RenderResult => render(ui, { wrapper: TestProviders, ...options });
```

The above test is failing when using `ChakraProvider`.

I believe it could be solved by adjusting a `mounted` conditional in `EnvironmentProvider` and making it like: `mounted && !node`. This is how I solved my issue for now, I made a patch using `patch-package`. However, I'm not aware of any potential issues it may cause. Maybe there is a better way of solving this issue.

### PR DESCRIPTION
**Pull request by yukukotani**
Closes #6374

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

`span` is rendered next to the children of `ChakraProvider`. This breaks some tests to check DOM structure.

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

`span` is rendered in the portal, so DOM structure of the component isn't affected.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

It seems that we can skip rendering `span` if `environmentProp` is given. I'll work on that in separate PR because it's not related to the issue.

### CODE REVIEW

**Comment by segunadebayo** [comment]
@yukukotani Kindly resolve the conflicts in this PR. I'd like to get this merged.

**Comment by yukukotani** [comment]
@segunadebayo Resolved. But lock file has large diff because of pnpm's version update. Is it ok?

**Comment by segunadebayo** [comment]
Thinking about this again. It seems to me that using a portal defeats the purpose of the env in the first place.

Its purpose is to get the correct reference to `window` or `document` regardless of the environment used. Portal will append to the `document.body` by default. The `document` might be incorrect in most cases.

The best way to test this is to render any component that uses the env within an iframe (using react-frame-component) and see if it still works as intended.

**Comment by yukukotani** [comment]
@segunadebayo I think this works because Portal also detects env by `tempNode`.

Anyway, we need tests for the env but it's not easy since [jsdom doesn't support iframe's srcdoc](https://github.com/jsdom/jsdom/issues/1892). `react-frame-component` doesn't work with React Testing Library.

e2e testing is one of the options.

**Comment by ksocha** [comment]
That might be a dumb proposition, but what if we just could prevent the `span` element being rendered after the node is set, like so:
```
{mounted && !node && (
        <span
          ref={(el) => {
            startTransition(() => {
              if (el) setNode(el)
            })
          }}
        />
      )}
```

**Comment by segunadebayo** [comment]
So far, setting the span to be `hidden` has worked, and I would leave it as is for now.

I'll use a Portal as a fallback implementation if this becomes an issue.

Thanks for your efforts on this one @yukukotani

**Pull request closed without merging**
