### PR TITLE
docs/mobile navigation

### PR DESCRIPTION
**Pull request by tioluwani94**
This PR adds bottom navigation on mobile devices for the website.

### CODE REVIEW

**Comment by with-heart** [comment]
I think something got checked in that's supposed to be ignored somehow. I don't think all those `page-data` files should be there.

**Comment by with-heart** [comment]
Yeah `public/` is in `website/.gitignore` but for some reason it's being included.

**Comment by segunadebayo** [comment]
Hey @tioluwani94, please delete the `doc/` folder on your end, and update the PR to add the mobile nav into the `website/` folder.

Thanks

**Comment by tioluwani94** [comment]
Alright I'll do that @segunadebayo

**Comment by tioluwani94** [comment]
Done @segunadebayo @with-heart

**Comment by with-heart** [comment]
@tioluwani94 That's much better! +67 lines instead of +30000 lol

**Comment by with-heart** [comment]
Looks so good Kola! Here's a screenshot: 
image

**Comment by tioluwani94** [comment]
Thanks @with-heart

**Pull request merged**
