### PR TITLE
chore: first pass at mobile nav

### PR DESCRIPTION
**Pull request by jmiazga**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by segunadebayo** [comment]
Thanks for this PR @jmiazga. I think we can do without the `constate` library except if there's some extra functionality you need it for.

What are your thoughts?

**Comment by jmiazga** [comment]
@segunadebayo Nope that was leftover from messing around with something before. Removed.

Thoughts on the icons and sponsor buttons on the bottom of the menu as well?

image

image

**Comment by santialbo** [comment]
The `IconButton` on `MobileNav` looks weird on small screens:
Screenshot 2020-09-04 at 10 48 24
Changing this
```
display={{ sm: "inline-flex", md: "none" }}
```
for this
```
display={{ base: "inline-flex", md: "none" }}
```
fixes it

**Comment by jmiazga** [comment]
@santialbo Good catch thanks!

**Comment by segunadebayo** [comment]
Thanks for this PR, @jmiazga.

I took some ideas from here and implemented a better design for the mobile nav.

**Pull request closed without merging**
