### PR TITLE
fix: numberInput stepping twice on mobile

### LINKED ISSUE #181: [NumberInput] incrementing twice
Every time I do some action on the `NumberInput` example on the [docs](https://chakra-ui.com/numberinput) (e.g. increase or decrease), it repeats the action. Example:

- Value is `2`, then I press the increase button once and it becomes `4` instead of `3`.

This happens on Google Chrome on Android, running MIUI 10.3.

### PR DESCRIPTION
**Pull request by zaguiini**
Fixes #181.

It will fix the behavior for the future `NumberInput` as we can re-use the logic

### CODE REVIEW

**Comment by segunadebayo** [comment]
Thank you for working on this @zaguiini.

I can't figure out how to get Storybook to work yet. For now, can you share a gif that shows it works? Just to be extra sure. Thanks

**Comment by zaguiini** [comment]
I managed to make it work using [ngrok](https://ngrok.com). Created a tunnel like that:
`./ngrok http 6006` with the Storybook server running. It will give you a link that you can get into your mobile device and test the behavior.

**Comment by segunadebayo** [comment]
Thanks.

**Comment by zaguiini** [comment]
Have you been able to test, @segunadebayo ?

**Comment by segunadebayo** [comment]
@zaguiini, not yet. I'd appreciate if you can help generate a link for me to confirm this before I merge.

**Comment by zaguiini** [comment]
Here you go, @segunadebayo: https://imgur.com/a/QnlmdzE

**Pull request merged**
