### PR TITLE
Docs/fix daily workflow pr

### PR DESCRIPTION
**Pull request by tomchentw**
@with-heart I saw you merged #4314. Unfortunately it contains bugs. This PR fixes them.

## 📝 Description

* Fixes workflow run order
* Fixes committing `website/avatars` folder

## ⛳️ Current behavior (updates)

The workflow failed: https://github.com/chakra-ui/chakra-ui/actions/runs/1043440696

## 🚀 New behavior

The workflow succeeds. This was tested on my forked repo:
https://github.com/tomchentw/chakra-ui/runs/3100486439

Here's the test branch with its generated commits: https://github.com/chakra-ui/chakra-ui/compare/main...tomchentw:docs/daily-workflow-fix

JPEG-1

## 💣 Is this a breaking change (Yes/No):

No.

### CODE REVIEW

**Comment by with-heart** [comment]
Thanks for fixing that! Prompt service 😁

**Comment by with-heart** [comment]
@tomchentw Are you on our Discord? Would love to chat more with you sometime. You've been doing some great work!

**Comment by tomchentw** [comment]
I should add the job.if check so that it only runs on github.repository is here

**Comment by tomchentw** [comment]
JPEG-1

`! [remote rejected]     main -> main (protected branch hook declined)`

https://github.com/chakra-ui/chakra-ui/runs/3148138804?check_suite_focus=true

**Pull request merged**
