### PR TITLE
Add Copy button to code snippets in readme

### PR DESCRIPTION
**Pull request by Lalit2005**
## 📝 Description

Added `Copy` button to code snippets in readme file

## 🚀 New behavior

When clicked on the `Copy` button, user will be taken to Copii's webpage and redirected back. You may test it to copy `hi` to clipboard👇

[copy](https://copii.vercel.app/?ct=hi&tm=blk&lg=https://avatars.githubusercontent.com/u/54212428?s=200&v=4)

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by dodas — COMMENTED** [review]
I honestly much dislike this.

How hard is it to ctrl+c? It definitely takes less time that waiting to be redirected to some site and back. And it brings more maintanence to us, to keep the encoded code in urls in sync.

**Comment by with-heart** [comment]
What's the benefit of the redirect that we don't get from a js-driven copy like most other sites use? Definitely would like to add easy copying, but the redirect feels strange.

**Comment by dodas** [comment]
Well, you can't put JS inside github readme :D

**Comment by with-heart** [comment]
Ohhhh, for some reason I was thinking this was for the getting started docs page. Derp

**Comment by segunadebayo** [comment]
Thank you for taking the time to create this PR @Lalit2005.

I think we can do without this as it adds more maintenance overhead for us. The good'ol copy+paste works.

**Pull request closed without merging**
