### PR TITLE
chore: fix new packages

### PR DESCRIPTION
**Pull request by with-heart**
This PR makes a few changes to resolve some build failure issues, and also updates the package name for `control-box` in its `README` and `package.json`

### CODE REVIEW

**Comment by with-heart** [comment]
Welp, this was working, but now I'm running into new build failures after rebasing again.

**Comment by segunadebayo** [comment]
@with-heart, I just fixed the issue. You can rebase again.

**Comment by segunadebayo** [comment]
@with-heart, please resolve conflict.

**Comment by with-heart** [comment]
@segunadebayo done!

**Pull request merged**
