### PR TITLE
fix: match media on useBreakpoint when no default value

### PR DESCRIPTION
**Pull request by stellarhoof**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

`useBreakpoint` uses `undefined` for its current breakpoint if no default value is passed, causing its effect to trigger a re-render when the current breakpoint gets updated to its correct value

## What is the new behavior?

`useBreakpoint` matches media on first render

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

### CODE REVIEW

**Comment by ljosberinn** [comment]
Besides CI crashing for unrelated reasons, I'm afraid this would crash server side as `window` is not available there.

**Comment by stellarhoof** [comment]
Hmm you're right. However there's already a `matchMedia` [here](https://github.com/chakra-ui/chakra-ui/blob/32a2e50f05083ba3c1b00c7b988ebbcfd997b224/packages/media-query/src/use-breakpoint.ts#L63). Doesn't that break on SSR too?

**Comment by ljosberinn** [comment]
useEffect doesnt run server side, hence it's safe to use there; you could incorporate  `isBrowser` in your changes

**Comment by stellarhoof** [comment]
@ljosberinn Done

**Pull request merged**
