### PR TITLE
docs: create TRIAGE overview document

### PR DESCRIPTION
**Pull request by with-heart**
I've been working on this for awhile and I need to stop and take a break. But I think it covers a lot of my thinking on triage and hopefully covers the topic pretty well so far.

Wanted to open this as a draft to hopefully get some feedback before I start working on it again.

### CODE REVIEW

**Comment by with-heart** [comment]
I think this is finally good to go. The document captures a lot of my thoughts around triage, and outlines the basic triage process.

**Review by codebender828 — APPROVED** [review]
Nice work here, @with-heart . 👍

**Comment by aaronmcadam** [comment]
This is awesome @with-heart!

Is there any guidance on how to decide if a component should be added to Chakra?

**Comment by with-heart** [comment]
@aaronadamsCA Nothing yet, but it's something I think we should have coming up in the future. Need to have a better process around things like that.

**Pull request merged**
