### PR TITLE
fix: #4251 layout flashing from useBreakpoint

### PR DESCRIPTION
**Pull request by nxtman123**
If `env.window.matchMedia` is available when the hook mounts, use it to find the initial state. This prevents the value changing the next "tick" after the hook mounts, often causing layout changes that look like flashes on the screen.

I am having trouble with the tests, the SSR test suite doesn't mock matchMedia, but it seems to be "working" and matching the "sm" breakpoint. In SSR it should return the default breakpoint as I have tested for `env.window.matchMedia`.

Addresses #4251

## 📝 Description

Even though `defaultBreakpoint` was added, the essential problem of an incorrect first value is still present.

## ⛳️ Current behavior (updates)

When useBreakpoint mounts, its first returned value is `defaultBreakpoint` or `undefined`, even when `window.matchMedia` is available.
Screen Shot 2021-12-10 at 2 36 17 PM

## 🚀 New behavior

When `window.matchMedia` is available, the first returned value is correct.
Screen Shot 2021-12-10 at 2 33 34 PM

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by nxtman123** [comment]
I used the codesandbox to show it working
Screen Shot 2021-12-10 at 2 33 34 PM

**Comment by nxtman123** [comment]
Demo sandbox https://codesandbox.io/s/create-react-app-ts-forked-88p78?file=/src/App.tsx:233-298

**Comment by primos63** [comment]
> I am having trouble with the tests, the SSR test suite doesn't mock matchMedia, but it seems to be "working" and matching the "sm" breakpoint. In SSR it should return the default breakpoint as I have tested for env.window.matchMedia.

@nxtman123 You can try the [mock](https://github.com/chakra-ui/chakra-ui/blob/main/packages/media-query/tests/matchmedia-mock-plus.ts) I created for `useMediaQuery`. Checkout the useMediaQuery [test](https://github.com/chakra-ui/chakra-ui/blob/main/packages/media-query/tests/use-media-query.test.ts) for usage.

**Comment by nxtman123** [comment]
> > I am having trouble with the tests, the SSR test suite doesn't mock matchMedia, but it seems to be "working" and matching the "sm" breakpoint. In SSR it should return the default breakpoint as I have tested for env.window.matchMedia.
> 
> @nxtman123 You can try the [mock](https://github.com/chakra-ui/chakra-ui/blob/main/packages/media-query/tests/matchmedia-mock-plus.ts) I created for `useMediaQuery`. Checkout the useMediaQuery [test](https://github.com/chakra-ui/chakra-ui/blob/main/packages/media-query/tests/use-media-query.test.ts) for usage.

Sorry, I meant to say that for the SSR test suite, matchMedia should **not** be available, but it is.

That suite doesn't mock matchMedia like the others do (as it should), but matchMedia still seems to be available to the hook.

**Comment by primos63** [comment]
The test for breakpoint include the matchMediaMock which is setup for all tests.
```js
describe("with object", () => {
  beforeAll(() => {
    matchMedia = new MatchMediaMock()
  })

  afterEach(() => {
    matchMedia.clear()
  })
```
That's why it's there for the SSR test. You probably need to breakout the SSR test into its own file which doesn't include the mock.

**Comment by nxtman123** [comment]
Thanks @primos63, that fixed the tests!

**Comment by nxtman123** [comment]
@primos63 Is there anything I've missed doing that I still need to do?

**Comment by jamesopti** [comment]
We've patched this over and it works great. Thanks for the contribution @nxtman123 !

Excited for this to get merged.

**Review by TimKolberger — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
