### PR TITLE
fix(use-breakpoint-value): fix hook when given array of values

### PR DESCRIPTION
**Pull request by candicecz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The useBreakpointValue hook does not work when provided with an array.

Fixes: #2184 

## What is the new behavior?

- The hook now works again when provided with an array.
- The storybook example as described in the issue works.
- The hook also works when given a custom breakpoint.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ljosberinn** [comment]
Hm that's odd. Why were the tests passing before then 🤔 https://github.com/chakra-ui/chakra-ui/blob/develop/packages/media-query/tests/use-breakpoint-value.test.tsx#L107

**Comment by candicecz** [comment]
So I think I can answer that.
The test "with-array" uses the following array as the test values.
 ```
const values = ["base", "sm", "md", "lg", "xl", "customBreakpoint"]
```

The original useBreakpointValue looks like this:
```
  const obj = isArray(values)
    ? fromEntries<Record<string, T>>(
        Object.entries(
          arrayToObjectNotation(values, breakpoints),
        ).map(([_, value]) => [value, value]),
      )
    : values
```
As you can see it uses the mapped value as the key as well.
This is not a problem with the test because `base`, `sm`, etc are valid keys.
However, in the media query stories the values are:
```
const values = ["red.500", null, "green.500"]
```
and the aforementioned code yields:
```
{red.500:"red.500", green.500: "green.500"}
```
which is not valid.

**Comment by candicecz** [comment]
I could change the test values if you want as well..

**Comment by ljosberinn** [comment]
Would be great - yeah, was about to write that haha. Would be great if we have a test case for that to not happen again, thanks in advance!

**Comment by candicecz** [comment]
I updated test, please check that I updated the values correctly. Thank you!

**Pull request merged**
