### PR TITLE
fix(layout): added flex gap property

### LINKED ISSUE #2720: Add support for flex gap
https://caniuse.com/flexbox-gap

Supported in Chrome and FF and will be supported in Safari next major release (currently in TP).

If approved I'm happy to make the changes.

### PR DESCRIPTION
**Pull request by MichaelKilbane**
Closes #2720

## 📝 Description

> This change enables the `gap` property to be used in the Flex component. At the time of submitting this, browser support for this feature is at [87.3%](https://caniuse.com/flexbox-gap).

## ⛳️ Current behavior (updates)

> When applying the `gap` property to the Flex component, it merely appends the key and value as an attribute on the HTML element.

## 🚀 New behavior

> Now, when applying the `gap` property to the Flex component, it will be correctly applied as a CSS style. It also attempts to resolve values as tokens from the 'space' token set.

## 💣 Is this a breaking change (Yes/No):

> No, unless someone wants a gap attribute on their HTML elements for some reason.

## 📝 Additional Information

> Fingers crossed this gets added. This property is a lifesaver and deserves full support.

### CODE REVIEW

**Comment by MichaelKilbane** [comment]
@segunadebayo Anything else I can do to get this over the line?

**Comment by segunadebayo** [comment]
@MichaelKilbane, the build is failing that's the only reason. I'm going to take a look shortly

**Comment by selrond** [comment]
@MichaelKilbane does this PR include rowGap and columnGap props / gap notations?

**Comment by anubra266** [comment]
can we merge this @segunadebayo

**Comment by selrond** [comment]
> @MichaelKilbane does this PR include rowGap and columnGap props / gap notations?

@anubra266 @segunadebayo 

Why not include [`rowGap`](https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap) & [`columnGap`](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap) as well? 

These are standard properties

**Comment by k-utsumi** [comment]
I want to use `gap` and not to use `gridGap`. Please merge it 😭
Of course I also want `rowGap` and` columnGap`, but they don't have to be now.

**Comment by TimKolberger** [comment]
Thank you for working on this @MichaelKilbane! 💖 
I branched off your PR and rebased it onto main and added the columnGap and rowGap properties.

@all-contributors please add @MichaelKilbane for code.

I am closing this PR in favor of #5123.

**Pull request closed without merging**
