### PR TITLE
docs: Fix minor typos in comparison.mdx

### PR DESCRIPTION
**Pull request by anantja-in**
## 📝 Description

Fixes minor typos in comparison doc.

### CODE REVIEW

**Review by dodas — APPROVED** [review]

**Comment by anantja-in** [comment]
@dodas Thanks for the review. How do I get another reviewer to give me a review so that I can merge this?

**Review by with-heart — APPROVED** [review]

**Comment by with-heart** [comment]
@anantja-in Just gotta wait unfortunately, most of us have been pretty busy with work/life lately.

Thanks for the fixes!

@allcontributors please add @anantja-in for docs

**Comment by anantja-in** [comment]
Thank you @with-heart — I'm really loving this project, and glad to start contributing here.

**Comment by dodas** [comment]
hey @anantja-in,

unless it's something urgent, just wait and it will get usually merged/reviewed shortly.
If you want to explicitly ask for a review, you can use the `Reviewers` feature in the top right corner of PR, but I don't think it will speed the process up 🙂

Screenshot 2021-02-17 at 15 57 58

**Comment by with-heart** [comment]
@anantja-in Glad to have you 😁

**Comment by anantja-in** [comment]
@dodas Thanks again. Got it. I usually look for the reviewers gear icon but it was missing for me (even before the second review). Might have something to do with the repo's settings? 🤔  (Either way, I think it's totally ok to not have that since y'all probably want to get to this repo's PR's at your cadence.)

Screen Shot 2021-02-17 at 7 02 01 AM

**Comment by with-heart** [comment]
Yeah, I think you have to be a member of the org to request a review. I think most of us have notifications turned on all for all repo activity, so it's usually just a matter of time until another one of us gets to something to review it.

**Pull request merged**
