### PR TITLE
Add accessible Carousel component

### LINKED ISSUE #200: Add accessible Carousel component
WAI-ARIA Authoring Practices has a [section](https://www.w3.org/TR/wai-aria-practices-1.1/#carousel) about building accessible carousel components:

> A carousel presents a set of items, referred to as slides, by sequentially displaying a subset of one or more slides. Typically, one slide is displayed at a time, and users can activate a next or previous slide control that hides the current slide and "rotates" the next or previous slide into view. In some implementations, rotation automatically starts when the page loads, and it may also automatically stop once all the slides have been displayed. While a slide may contain any type of content, image carousels where each slide contains nothing more than a single image are common.

I think there is a great opportunity to build a composable component by following [Reach UI's Philosophy](https://gist.github.com/ryanflorence/e5c794e6093d16a69fa88d2112a292f7). As I've observed, there are several layers of abstraction:

- Carousel – Similar to Reach UI's Dialog, it would just wrap the 2 children below
  - CarouselControls – [Contains](https://www.w3.org/TR/wai-aria-practices-1.1/#terms) Rotation Control, Next Slide Control, Previous Slide Control and Slide Picker Controls
  - CarouselRotator – Touch-controllable scroll container with a hidden scrollbar
    - CarouselSlide – Holds content to be presented

I've already started building the foundation of some components above, mostly by following [a CSS-Tricks article](https://css-tricks.com/can-get-pretty-far-making-slider-just-html-css/) about [Scroll Snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap):

#### CarouselRotator

```tsx
import { Flex, FlexProps } from '@chakra-ui/core';
import React from 'react';
import { MarginProps, ResponsiveValue } from 'styled-system';
import CarouselSlide from './CarouselSlide';

// TODO: https://www.w3.org/TR/wai-aria-practices-1.1/#grouped-carousel-elements

function negateResponsiveValue<T>(value: ResponsiveValue<T>) {
  if (value == null) return value;
  if (typeof value === 'number') return -value;
  if (typeof value === 'string') return `-${value}`;
  if (Array.isArray(value)) return value.map(v => (v != null ? `${-v}` : v));
  return Object.fromEntries(
    Object.entries(value).map(([k, v]) => [k, v != null ? `${-v}` : v]),
  );
}

export interface CarouselProps extends FlexProps {
  children: React.ReactComponentElement<typeof CarouselSlide>[];
  slideIndex?: number;
  spacing?: MarginProps['margin'];
  spacingX?: MarginProps['mx'];
  spacingY?: MarginProps['my'];
}

export default function Carousel({
  children,
  slideIndex = 0,
  spacing,
  spacingX,
  spacingY,
  ...restProps
}: CarouselProps) {
  return (
    <Flex
      as="section"
      aria-roledescription="carousel"
      aria-live="polite" // The carousel is NOT automatically rotating
      my={negateResponsiveValue(spacingY != null ? spacingY : spacing)}
      overflow="auto"
      css={{
        scrollSnapType: 'x mandatory',
        // TODO: Leave vendor prefixing to the underlying library
        '::-webkit-scrollbar': { width: 0 },
        '-msOverflowStyle': 'none',
        scrollbarWidth: 'none',
      }}
      {...restProps}
    >
      {React.Children.map(children, (child, i) =>
        React.cloneElement(child, {
          inert: i !== slideIndex ? '' : undefined,
          px: spacingX != null ? spacingX : spacing,
          py: spacingY != null ? spacingY : spacing,
        }),
      )}
    </Flex>
  );
}
```

There is still a lot of work to do, e.g. adding support for automatic rotating by setting `aria-live` to `off`.

#### CarouselSlide

```tsx
import { Box, BoxProps } from '@chakra-ui/core';
import React from 'react';

// TODO: Follow the status of https://github.com/WICG/inert and remove polyfill
import 'wicg-inert';

export default function CarouselSlide({
  children,
  inert,
  ...restProps
}: BoxProps) {
  return (
    <Box
      role="group"
      aria-roledescription="slide"
      flex="0 0 100%"
      css={{ scrollSnapAlign: 'center' }}
      {...restProps}
    >
      {/* TODO: Remove extra `div` once `shouldForwardProp` of `Box` supports `inert` */}
      <div inert={inert}>{children}</div>
    </Box>
  );
}
```

The `inert` attribute is required to disable tab navigation to undisplayed slides.

#### declarations.d.ts

Unfortunately, TypeScript and React don't support the `inert` attribute yet, thus, it cannot be specified as a boolean, [but an empty string: `''`](https://github.com/WICG/inert#2-toggle-inert-on-an-element).

```ts
declare module 'react' {
  interface DOMAttributes<T> {
    inert?: '' | undefined;
  }
}

declare global {
  namespace JSX {
    interface IntrinsicAttributes {
      inert?: '' | undefined;
    }
  }
}

export {};
```

### PR DESCRIPTION
**Pull request by kripod**
Resolves #200

### CODE REVIEW

**Comment by kripod** [comment]
@segunadebayo I've updated the PR to include the latest improvements. No significant updates should be expected soon. Please be aware that type definitions are not aligned to the new typings.

**Comment by kripod** [comment]
_Note to self: For managing state through Context, [constate](https://github.com/diegohaz/constate) may be a great library._

**Comment by LouiseReid** [comment]
Do you have a timeframe for when this is likely to go live? Would really like to try it out

**Comment by kripod** [comment]
As it currently stands, I'm waiting for the migration of Chakra towards TypeScript. There are also some major flaws in the implementation regarding performance, which shall also be investigated.

**Comment by segunadebayo** [comment]
@kripod, this PR is pretty stale and might not make it to the next release considering there's still some work to do on it.

I'm happy to complete it after the next release, but I'll close it out for now.

**Comment by kripod** [comment]
Good decision, thank you for helping!

**Comment by iamyuu** [comment]
Hi, any updates on this?

**Pull request closed without merging**
