### PR TITLE
feat(gatsby-plugin-chakra-ui): create gatsby plugin for chakra ui

### PR DESCRIPTION
**Pull request by alexluong**
#151

# gatsby-plugin-chakra-ui

Please read over `packages/gatsby-plugin-chakra-ui/README.md` for basic idea and instruction.

You can run `yarn workspace gatsby-starter-chakra-ui start` to see the example site. Feel free to make changes to it as you see fit.

## Included in this PR
- [x] Created Gatsby plugin
- [x] Created example Gatsby site that makes use of that plugin
- [x] Wrote README documentation for the plugin

## Questions

- Let me know what you think about the general approach as well as the Gatsby options design (`isResettingCSS` and `isUsingColorMode` options).
- Am I missing anything? Something I should have done?

### CODE REVIEW

**Comment by alexluong** [comment]
@segunadebayo Resolved

**Comment by alexluong** [comment]
If you're going to tweet about the Gatsby integration, I'd appreciate a mention in the tweet. My Twitter is `@alex__luong`. Thanks! Looking forward to the package.

**Comment by alexluong** [comment]
Hey @segunadebayo, thanks to @Sonicrida, we found out that we need to put `CSSReset` inside `ColorModeComponent`. I pushed a fix for this.

**Comment by Sonicrida** [comment]
I'm glad that we could figure that out! 🎯

**Comment by segunadebayo** [comment]
Thank you for your work on this @alexluong and @Sonicrida

**Pull request merged**
