### PR TITLE
fix: popover z-index

### PR DESCRIPTION
**Pull request by theVedanta**
Closes # 

## 📝 Description
Z-Index added in Popover which is taken from the indices object

## ⛳️ Current behavior (updates)
Functions in accordance to passed index

## 🚀 New behavior
Functions wrt given popover index

## 💣 Is this a breaking change (Yes/No):
No

In reference to #7408

### CODE REVIEW

**Comment by krvajal** [comment]
I think the zIndex needs to be applied to the parent div, the one with the class `chakra-popover__popper`

**Comment by krvajal** [comment]
I created a fix here https://github.com/chakra-ui/chakra-ui/pull/7432

**Comment by vitalijalbu** [comment]
Hi @krvajal, popover still have **z-index** problems, I'm using latest chakra ui version: see here: https://turo.vercel.app/search

**Comment by Nishchit-Dev** [comment]
please anyone can explain issue here!

**Comment by Nishchit-Dev** [comment]
any thing visual will be help full

**Comment by krvajal** [comment]
> Hi @krvajal, popover still have **z-index** problems, I'm using latest chakra ui version: see here: https://turo.vercel.app/search

Indeed it does, fix is not merged

**Comment by segunadebayo** [comment]
Thanks for working on this.

This has been incorporated into the upcoming v3 version

**Comment by j-vitali** [comment]
> Thanks for working on this.
> 
> This has been incorporated into the upcoming v3 version

any idea of release date of v3? 👀

**Pull request closed without merging**
