### PR TITLE
fix(modal): fix shifting screen when opening modal

### LINKED ISSUE #6084: Components that use react-remove-scrollbar shift screen
### Description

Since Chakra v2, any component that uses react-remove-scrollbar (modal, drawer), when open, it shifts the html body

### Link to Reproduction

https://chakra-ui.com/docs/components/overlay/modal

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/components/overlay/modal
2. Click on any 'open modal'
3. See page shift to the left because there is a padding-right and margin-right being applied.

### Chakra UI Version

2.1.0

### Browser

Chrome latest, Safari latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This issue can be reproduced in the docs page. When interacting with V1.8.8 docs, the issue is not there. Not sure if it has to do with the `react-remove-scrollbar` package (since it was updated in Chakra v2), or within Chakra code.

### PR DESCRIPTION
**Pull request by itkrt2y**
Closes #6084

## 📝 Description

Update react-remove-scroll to fix shifting screen when opening modal

## ⛳️ Current behavior (updates)

When opening modal, it shifts the html body.

## 🚀 New behavior

Works as expected (not shift body)

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

- Related PR: https://github.com/theKashey/react-remove-scroll-bar/pull/32
- Test sandbox: https://codesandbox.io/s/fix-shifting-screen-91vorj

### CODE REVIEW

**Comment by Nithur-M** [comment]
Hi, this issue still persists. I am using Chakra v2.2.3
Image link: https://ibb.co/wcMgNV0

**Comment by a4addel** [comment]
> I am using Chakra v2.2.3
Update to v2.2.8

**Comment by JeromeMTR** [comment]
Hi I'm using chakra v2.3.1 and still getting the body shift

**Comment by a4addel** [comment]
Guys update to `v2.2.8`.

**Comment by wub** [comment]
Hey @segunadebayo @itkrt2y this is still broken in Chakra 2.5.0, should I raise this issue with react-remove-scroll instead?

image

**Comment by lucastnr** [comment]
I'm still facing this issue on the latest version (2.8.0)

**Comment by lucastnr** [comment]
For everyone facing this, you can just set blockScrollMount (check [doc](https://chakra-ui.com/docs/components/modal/props)) as `false`, but on the other hand, the user will be able to scroll the page behind the Modal.

image

**Comment by shyam-ayrshare** [comment]
The workaround with setting `blockScrollMount` to `false` doesn't work for me with drawers placed on the right side. Only seems to be working for drawer placed on the left.

**Comment by sebas1803** [comment]
image

Same issue here.

**Pull request merged**
