### PR TITLE
 feat(color-mode): add option to specify domain

### PR DESCRIPTION
**Pull request by AshMW2724**
## 📝 Description

Add option to specify domain in the `createCookieStorageManager` function.

## ⛳️ Current behavior (updates)

Defaults to current domain.

## 🚀 New behavior

Allows domain to be specified.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

This is a feature I would find extremely useful as I use an app that uses multiple sub-domains.

```js
createCookieStorageManager('themeMode', undefined, '.example.com')
                                                 // ^^ Adds this option
```

### CODE REVIEW

**Comment by AshMW2724** [comment]
🥲

**Comment by jack-glenn** [comment]
Amber Terd

**Comment by AshMW2724** [comment]
After actually testing the changes I proposed I have found out that the ColorModeScript will also need this to be added to it. Going to make those changes now.

**Comment by segunadebayo** [comment]
Closing this due to inactivity

**Pull request closed without merging**
