### PR TITLE
feat: create official storybook-addon package

### LINKED ISSUE #2694: Create official Chakra UI Storybook addon
The goal of this issue is to create an official Storybook preset addon for Chakra UI. Offering an official preset means that users need only install the preset to quickly get up and running with Chakra inside Storybook.

# Tasks

- [ ] Automatically decorate stories with `ChakraProvider`
- [ ] Enable customization of `ChakraProvider`
	- [ ] Custom `theme`
	- [ ] `resetCSS`, `portalZIndex`, etc. props
- [ ] Handle overriding Storybook `emotion` package conflicts? (see https://github.com/storybookjs/storybook/issues/13114 and #2527 for more context)
- [ ] Dogfood the preset package for our own internal Storybook setup (the ultimate test!)

# Possible stretch goals

- Add a color mode toggle button to the UI Toolbar to allow users to quickly switch color mode of the current story

### PR DESCRIPTION
**Pull request by with-heart**
Closes #2694 

## 📝 Description

This PR creates an official [Storybook Addon](https://storybook.js.org/docs/react/configure/storybook-addons) for Chakra UI! This will allow our users to configure their project Storybook to automatically wrap their stories with `ChakraProvider`.

### Installation & Configuration

Users will need to first install `@chakra-ui/storybook-addon`, and then add the addon to their Storybook `addons` configuration in their `.storybook/main.js` file:

```javascript
// .storybook/main.js

module.exports = {
  addons: ['@chakra-ui/storybook-addon'],
}
```

Users can specify global parameters for the addon in the `.storybook/preview.js` file. These options are the same as the props to `ChakraProvider` (minus `children`, of course), allowing the user to configure `ChakraProvider` for their stories in the same way they would in their application:

```javascript
// .storybook/preview.js

const theme = require('../theme')

export const parameters = {
  chakra: {
    theme,
  },
},
```

## ☑️ Remaining Tasks

- [x] Create `storybook-addon` package
- [x] Create `withChakra` decorator
- [x] Apply `withChakra` decorator to all stories automatically
- [x] Allow users to configure the addon
  - [x] Via global options
  - [x] Via individual story `parameters`
- [x] Set up package dependencies
- [x] Figure out how to make this thing build correctly
- [ ] Dogfood addon in internal Chakra storybook config (the ultimate test!)
- [x] Write a `README.md`
- [ ] Write a detailed changeset
- [ ] Write a guide page in the docs
- [ ] Manually publish a canary version (?)

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

I'd like for this addon to include UI customization to allow color mode and direction (ltr, rtl) to be toggled via buttons in the Storybook toolbar. I might make those non-MVP features though, depending on time.

Also I'm building this in public! You can follow along over on Twitter: https://twitter.com/grow_love/status/1371424661976846336

### CODE REVIEW

**Comment by with-heart** [comment]
We're pretty close to this being ready I think! Working on a few more tests to make sure that everything works perfectly with the internal Chakra Storybook and a bit more documentation to write, and then I'll move this out of draft status

**Comment by segunadebayo** [comment]
Since there's not much progress on this PR @with-heart. I'm going to close it for now.

Feel free to re-open when you resume work on it.

**Comment by PeterEckIII** [comment]
@with-heart, any updates on this PR? I'm interested in implementing this in my current project. Thanks!

**Comment by valerius21** [comment]
@PeterEckIII 

As far as I know, he wanted to build this addon in public. However, recent Twitter activity indicates that he is currently not pursuing this project. 

My approach:

### Option 1: Use a 3rd party addon

I have had some luck with the  [@snek-at/storybook-addon-chakra-ui](https://www.npmjs.com/package/@snek-at/storybook-addon-chakra-ui) addon. 

### Option 2: Use your own config

However, since I wanted to use Chakra UI in conjunction with TailwindCSS in Storybook, I was forced to adjust the storybook-internal Webpack config; too many unresolved CSS errors were why I went with this approach instead.

```js
// main.js
module.exports = {
  stories: [
    '../src/**/*.stories.@(ts|tsx|js|jsx)',
    '../src/lib/**/*.stories.mdx',
    '../src/lib/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-links',
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss')
        }
      }
    },
  ],
  core: { builder: 'webpack5' },
  webpackFinal: async (config) => { // the Chakra UI-critical part
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": "@emotion/react",
          "emotion-theming": "@emotion/react",
        },
      },
    };
  },
};
```

```js
// preview.js
import { ThemeProvider } from "../src/lib/theme-provider/theme-provider"

export const parameters = {
	actions: { argTypesRegex: "^on[A-Z].*" },
}

const ThemeDecorator = (Story) => (
	<ThemeProvider>
		<Story />
	</ThemeProvider>
)

export const decorators = [ThemeDecorator]
```

 ```tsx
// theme-provider.tsx
import React, { FC } from 'react';
import { ChakraProvider, ChakraProviderProps } from '@chakra-ui/react';
import 'tailwindcss/tailwind.css';
import '@fontsource/source-serif-pro'; // fonts can be imported now.

import { defaultTheme } from '../theme';

export type ThemeProviderProps = ChakraProviderProps & {
  children?: React.ReactNode;
};

/**
 * Apply all UI themes to the application.
 */

export const ThemeProvider: FC<ThemeProviderProps> = (
  { children, theme = defaultTheme },
  props
) => (
  <ChakraProvider theme={theme} {...props}>
    {children}
  </ChakraProvider>
);
```

**Comment by PeterEckIII** [comment]
@valerius21 , thanks for the link to that extension. I was able to successfully install that and get everything working!

**Comment by ngxCoder** [comment]
@with-heart Can I resume your work? I created a storybook addon to chakra UI to solve an issue some days ago, and the code is ready...
I want to check an issue related to the colors; even you could help me with the details

**Comment by ngxCoder** [comment]
Apparently, he's taking a break; I will try to complete this tonight 🔥🔥🔥

**Comment by valerius21** [comment]
@ngxCoder I'm excited to see your addon! :)

**Pull request closed without merging**
