### PR TITLE
feat(image): image lazy loading support

### PR DESCRIPTION
**Pull request by Andu033**

### CODE REVIEW

**Comment by with-heart** [comment]
Thanks @Andu033! 

The prop is fine but looking at it a little more, I'm not sure this will work with `Image`, at least how it is now.

https://github.com/chakra-ui/chakra-ui/blob/ac52c0e2d42da1d048b710d60c22aea9b80896ce/packages/image/src/image.tsx#L77-L101

What does it mean to have `loading="lazy"` if we render `fallbackSrc`? To make that actually work, you'd need to pass `ignoreFallback` every time in order to get `useImage` to return `loaded` status. 

@segunadebayo, do you think we should we modify `useImage` to check for the `loaded` prop and always return `loaded` status if it exists?

**Comment by segunadebayo** [comment]
Thanks for this @Andu033 

yes, it makes sense to bypass the `useImage` hook if the `loading` prop is passed, it's always better to allow the browser handle image the loading strategy.

In this scenario, we can't apply `fallbackSrc`. We'll push all work to the native `img` tag.

What do you guys think?

**Comment by with-heart** [comment]
@segunadebayo That makes perfect sense. I'm going to go ahead and merge this. I created #1027 to follow up on implementing the new flow around `loading` now that it's in place.

**Comment by sebqq** [comment]
Hello @Andu033 , I would like to ask you if SSR is supported?

**Comment by with-heart** [comment]
@all-contributors please add @Andu033 for code

**Comment by lcswillems** [comment]
@with-heart I don't understand the reasonning here

For me it makes sense to have a fallback and `loading="lazy"`. I want to have the fallback displayed whenever the image is not loaded. And I want `loading="lazy"` to trigger the loading of the image as soon as the image is visible.

**Pull request merged**
