### PR TITLE
feat(ci): add lighthouse on docs publish

### PR DESCRIPTION
**Pull request by ljosberinn**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

runs LightHouse after a deploy of the website/docs

## Other information

_Should_ work out of the box. Only thing I'm unsure of is the interpolation of the URL here:

```sh
"https://api.zeit.co/v5/now/deployments?limit=1&teamId=${{ secrets.ORG_ID }}"
```

as well as the current min requirements:
```sh
          minAccessibilityScore: "90"
          minBestPracticesScore: "90"
          minPerformanceScore: "90"
          minProgressiveWebAppScore: "90"
          minSeoScore: "90"
```

### CODE REVIEW

**Comment by with-heart** [comment]
I love this. I don't think `ORG_ID` is available though. I think @segunadebayo would need to copy that from Vercel and make it available in the org secrets.

**Comment by ljosberinn** [comment]
Oh I thought they are already available, alright. For reference, this is how to retrieve those values (you can't see them in Vercel, or at least not as a regular user, maybe you can as team):

> `VERCEL_PROJECT_ID` and `VERCEL_ORG_ID` can be retrieved from your projects `.vercel/project.json` file.
> For that, you will need to globally install the [Vercel CLI](https://vercel.com/docs/cli#getting-started):
> ```js
> npm i -g vercel
> ```
> After logging in, in your project simply execute `vercel`, it will create the required file (more info [here](https://github.com/amondnet/vercel-action#project-linking)).

**Comment by segunadebayo** [comment]
@ljosberinn, what's the status with this?

**Comment by ljosberinn** [comment]
You'd need to add those github secrets to be able to test this unless they are already present. I can rebase in a sec.

**Comment by ljosberinn** [comment]
Right, I totally forgot we don't deploy through github anymore 🤔 guess this is redundant then.

**Comment by segunadebayo** [comment]
Yes, it's now redundant.

Thank you for the efforts though.

**Pull request closed without merging**
