### PR TITLE
fix: Introduce cross-env for BABEL_ENV assignment

### LINKED ISSUE #891: Build fails on Windows due to BABEL_ENV unix style assignment
Windows can't handle ```BABEL_ENV=``` style of assignments and fails with 
```
[build:cjs] 'BABEL_ENV' is not recognized as an internal or external command,
[build:cjs] operable program or batch file.
[build:esm] 'BABEL_ENV' is not recognized as an internal or external command,
[build:esm] operable program or batch file.
```

Expecting the build pipe to work on windows with just yarn build on "any" terminal. 

**Link to minimal reproduction**

**Steps to Reproduce**
yarn bootstrap
yarn build
on a windows machine.

**Suggested solution(s)**
Add cross-env as a dev dependency and replace BABEL_ENV= with cross-env BABEL_ENV.

**Desktop (please complete the following information):**

Windows

### PR DESCRIPTION
**Pull request by Psvensso**
Fixes #891
Replaced `BABEL_ENV ` with `cross-env BABEL_ENV` in packages/**/package.json
Added cross-env to root devDependencies
Updated utility script

Tested with normal setup procedures and build script. yarn bootstrap > yarn build
On Windows.
Needs a Unix test to make sure nothing was introduced.

### CODE REVIEW

**Comment by segunadebayo** [comment]
Thank you for this @Psvensso.

@cschroeter can you help review this?

**Comment by cschroeter** [comment]
The changes are fine. But I wonder who develops on Windows and doesn't use [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)
The downside of `cross-env` is that the NPM scripts are difficult to read, especially if several variables are added over time.

**Comment by Psvensso** [comment]
It's true that WSL works, i built it without problems on my machine at home. My workplace desktop doesn't have WSL, dunno if WSL usage is very common in the windows dev world though. My guess is that you will get plenty of issues around this when people try to build on "out of the box" windows machines. 

But whatever, up to you. 
At least consider adding it to the contrib readme.

**Comment by segunadebayo** [comment]
@Psvensso, sounds good. Kindly resolve conflicts.

**Comment by segunadebayo** [comment]
@all-contributors add @Psvensso for code

**Pull request merged**
