### PR TITLE
chore: remove deep imports

### PR DESCRIPTION
**Pull request by matt-tingen**
No issue

## 📝 Description

Removes deep imports that prevent storybook from building

## ⛳️ Current behavior (updates)

Storybook prints errors like:

```
Module not found: Error: Can't resolve '@chakra-ui/hooks/use-animation-state' in '<snip>/chakra-ui/packages/menu/src'
```

## 🚀 New behavior

Storybook builds successfully

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by takethefake — APPROVED** [review]
Hej @matt-tingen thanks for your contribution!

LGTM!

**Review by TimKolberger — APPROVED** [review]
LGTM!

Note to self: Add changeset before merging.

**Comment by TimKolberger** [comment]
Hi @matt-tingen,
just looking again over the changes and noticed that the import should be valid.
We started using multiple entrypoints for the hooks package to reduce the bundle size for dependent packages.

E.g.

```ts
import X from '@chakra-ui/hooks/use-animation-state' // should be valid
```

Could you share a reproduction of the issue you experienced + which version of chakra ui and storybook are you using?

**Comment by matt-tingen** [comment]
@TimKolberger Apologies if it wasn't clear but the errors encountered are from running chakra's storybook. On a fresh clone of 0542b8a53425093f18fd86d2b55220d3fa20253a I get lots of the following output when running `yarn storybook` after `yarn`.

```
[...]
              Field 'browser' doesn't contain a valid alias configuration
              resolved symlink to <snip>/chakra-ui/packages/hooks/use-animation-state.mjs
                using description file: <snip>/chakra-ui/packages/hooks/package.json (relative path: ./use-animation-state.mjs)
                  no extension
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs doesn't exist
                  .mjs
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs.mjs doesn't exist
                  .js
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs.js doesn't exist
                  .jsx
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs.jsx doesn't exist
                  .ts
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs.ts doesn't exist
                  .tsx
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs.tsx doesn't exist
                  .json
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs.json doesn't exist
                  .cjs
                    Field 'browser' doesn't contain a valid alias configuration
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs.cjs doesn't exist
                  as directory
                    <snip>/chakra-ui/packages/hooks/use-animation-state.mjs doesn't exist
              <snip>/chakra-ui/node_modules/@chakra-ui/hooks/use-animation-state.mjs doesn't exist
            .js
[...]
                      Field 'browser' doesn't contain a valid alias configuration
                      resolved symlink to <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs
                        using description file: <snip>/chakra-ui/packages/hooks/use-animation-state/package.json (relative path: ./index.cjs)
                          no extension
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs doesn't exist
                          .mjs
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs.mjs doesn't exist
                          .js
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs.js doesn't exist
                          .jsx
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs.jsx doesn't exist
                          .ts
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs.ts doesn't exist
                          .tsx
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs.tsx doesn't exist
                          .json
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs.json doesn't exist
                          .cjs
                            Field 'browser' doesn't contain a valid alias configuration
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs.cjs doesn't exist
                          as directory
                            <snip>/chakra-ui/packages/hooks/use-animation-state/index.cjs doesn't exist
                      <snip>/chakra-ui/node_modules/@chakra-ui/hooks/use-animation-state/index.cjs doesn't exist
[...]
```

Buried in the output are the following errors:

```
ERROR in ./packages/menu/src/use-menu.ts
Module not found: Error: Can't resolve '@chakra-ui/hooks/use-animation-state' in '<snip>chakra-ui/packages/menu/src'
 @ ./packages/menu/src/use-menu.ts 31:0-73 189:23-40
 @ ./packages/menu/src/index.ts
 @ ./packages/menu/index.ts
 @ ./packages/react/src/index.tsx
 @ ./packages/react/index.ts
 @ ./.storybook/preview.tsx
 @ ./.storybook/preview.tsx-generated-config-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js ./.storybook/preview.tsx-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./packages/popover/src/use-popover.ts
Module not found: Error: Can't resolve '@chakra-ui/hooks/use-animation-state' in '<snip>chakra-ui/packages/popover/src'
 @ ./packages/popover/src/use-popover.ts 26:0-73 108:17-34
 @ ./packages/popover/src/index.ts
 @ ./packages/popover/index.ts
 @ ./packages/react/src/index.tsx
 @ ./packages/react/index.ts
 @ ./.storybook/preview.tsx
 @ ./.storybook/preview.tsx-generated-config-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js ./.storybook/preview.tsx-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

Are these deep imports expected to work internally, as well? These are the only two I could find and changing them allows SB to run without errors.

Perhaps it's related to node or yarn version? I'm on node 16.13.0 and yarn 1.22.17

**Comment by TimKolberger** [comment]
Thanks for the clarification!

Have you tried building the codebase beforehand? 

My workflow is yarn build for every new PR or branch I checkout and then start `yarn preconstruct watch`.

This seems to be working for me.

Storybook is able to bundle simpler codebases on its own, but with the use of multiple entrypoints we might have exceeded its capabilities.

**Comment by matt-tingen** [comment]
I have built the project before but not in some time.

Using your workflow of `yarn build`, `yarn preconstruct watch`, and `yarn storybook` does allow SB to build for me. Is there benefit to bundle size by using the deep imports internally? If not, it may be beneficial to knock out these two instances and forbid them with a lint rule to keep just `yarn storybook` working. Otherwise, I could update `CONTRIBUTING` to reflect the extra steps necessary if that works for you.

**Comment by TimKolberger** [comment]
Yes there is a bundle size improvement when using e.g. the menu package stand-alone. We are planning to increase the number of multiple entrypoints to get even more bundle size improvements. Removing them would not be beneficial.

> Otherwise, I could update CONTRIBUTING to reflect the extra steps necessary if that works for you.

This would be awesome 👏💖
Thanks in advance 😊

**Comment by matt-tingen** [comment]
Superseded by https://github.com/chakra-ui/chakra-ui/pull/5624

**Pull request closed without merging**
