### PR TITLE
fix: use pseudo element instead of pseudo class

### PR DESCRIPTION
**Pull request by wonism**
#534

### CODE REVIEW

**Comment by segunadebayo** [comment]
@wonism, thanks for this PR. What's the rationale for this?

**Comment by wonism** [comment]
@segunadebayo, As I described in #534 

Pseudo element is a selector for specifying a part of the element.
Pseudo class is a selector for specifying a special state of selected element.

In case of before/after content inside of an element, pseudo element is more semantically correct than pseudo class.

And we should use **double colons(::)** for pseudo element. not a single colon(:). This distinguishes pseudo class from pseudo element.

---

Specification of pseudo elements. See:
https://www.w3.org/TR/selectors-3/#pseudo-elements

**Comment by segunadebayo** [comment]
@wonism, I see what you mean. Thanks for the clarification.

One thing though, can you PR against the `dev-ts` branch?  We're no longer merging changes to master to help us focus on the next release.

This is the file you're looking for: https://github.com/chakra-ui/chakra-ui/blob/dev-ts/packages/parser/src/configs/pseudo.selector.ts

Thanks

**Comment by wonism** [comment]
@segunadebayo, Sure. I re-created a PR. #552

**Pull request closed without merging**
