### PR TITLE
fix bad path in accordion/package.json

### PR DESCRIPTION
**Pull request by capaj**
this broke my parcel bundling

```
> parcel build frontend/src/index.html

🚨 Build failed.
@parcel/core: Failed to resolve '@chakra-ui/accordion' from './node_modules/@chakra-ui/core/dist/esm/index.js'
/home/capaj/work-repos/4house/4house-be-admin/node_modules/@chakra-ui/core/dist/esm/index.js:34:15
  33 | export * from "@chakra-ui/tooltip";
> 34 | export * from "@chakra-ui/accordion";
>    |               ^^^^^^^^^^^^^^^^^^^^^^
  35 | export * from "@chakra-ui/alert";
  36 | export * from "@chakra-ui/button";
@parcel/resolver-default: Could not load './dist/esm/index/js' from module '@chakra-ui/accordion' found in package.json#module
/home/capaj/work-repos/4house/4house-be-admin/node_modules/@chakra-ui/accordion/package.json:69:13
  68 |   "main": "dist/cjs/index.js",
> 69 |   "module": "dist/esm/index/js",
>    |             ^^^^^^^^^^^^^^^^^^^ './dist/esm/index/js' does not exist, did you mean './dist/esm/index.js'?'
  70 |   "name": "@chakra-ui/accordion",
  71 |   "peerDependencies": {
```

### CODE REVIEW

**Comment by capaj** [comment]
@with-heart any idea when does this get into a release? There were 2 releases since the merge and it's still broken in those npm packages.

**Comment by with-heart** [comment]
@capaj Huh, this should have made it into one or both or those releases at this point. I'll do a little digging and see if I can figure it out

**Comment by lebowski7** [comment]
Hi @with-heart , please did  you find out anything related to this? I'm struggeling with this issue as well. Thanks!

**Comment by with-heart** [comment]
@capaj @lebowski7 You're still receiving exact error in the description on `1.0.0@next.4`?

**Comment by capaj** [comment]
@with-heart yes, this is how package.json for accordion looks like in my node_modules:

```
{
  "_from": "@chakra-ui/accordion@^1.0.0-next.4",
  "_id": "@chakra-ui/accordion@1.0.0-next.2251",
  "_inBundle": false,
  "_integrity": "sha512-jjl2kroLtHWzS/Jk91J27SO9/iK8/wORNbyy5Q0tr0YGW2wRQ5l+IJDgnw3RJuR/MFJQxMNJVVDold+BVFu9Ug==",
  "_location": "/@chakra-ui/accordion",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "@chakra-ui/accordion@^1.0.0-next.4",
    "name": "@chakra-ui/accordion",
    "escapedName": "@chakra-ui%2faccordion",
    "scope": "@chakra-ui",
    "rawSpec": "^1.0.0-next.4",
    "saveSpec": null,
    "fetchSpec": "^1.0.0-next.4"
  },
  "_requiredBy": [
    "/@chakra-ui/core"
  ],
  "_resolved": "https://registry.npmjs.org/@chakra-ui/accordion/-/accordion-1.0.0-next.2251.tgz",
  "_shasum": "e4eab4df62cde65efbcc13a1995de6f19e43624d",
  "_spec": "@chakra-ui/accordion@^1.0.0-next.4",
  "_where": "/home/capaj/work-repos/4house/4house-be-admin/node_modules/@chakra-ui/core",
  "author": {
    "name": "Segun Adebayo",
    "email": "sage@adebayosegun.com"
  },
  "bugs": {
    "url": "https://github.com/chakra-ui/chakra-ui/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@chakra-ui/collapse": "^1.0.0-next.0",
    "@chakra-ui/descendant": "^1.0.0-next.0",
    "@chakra-ui/hooks": "^1.0.0-next.0",
    "@chakra-ui/icon": "^1.0.0-next.0",
    "@chakra-ui/utils": "^1.0.0-next.0"
  },
  "deprecated": false,
  "description": "A simple and accessible accordion component for React & Chakra UI",
  "devDependencies": {
    "@chakra-ui/system": "^1.0.0-next.0"
  },
  "files": [
    "dist"
  ],
  "gitHead": "57db7fd9e7b7c3c6465adfe3c91677c52841963e",
  "homepage": "https://github.com/chakra-ui/chakra-ui#readme",
  "keywords": [
    "react",
    "component",
    "accordion",
    "chakra",
    "chakra ui",
    "collapse",
    "accessible",
    "accessibility",
    "wai-aria",
    "aria",
    "a11y"
  ],
  "license": "MIT",
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index/js",
  "name": "@chakra-ui/accordion",
  "peerDependencies": {
    "@chakra-ui/system": "1.0.0-next.0",
    "react": "16.x"
  },
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/chakra-ui/chakra-ui.git"
  },
  "scripts": {
    "build": "concurrently yarn:build:*",
    "build:cjs": "cross-env BABEL_ENV=cjs babel src --root-mode upward --extensions .ts,.tsx -d dist/cjs --source-maps",
    "build:esm": "cross-env BABEL_ENV=esm babel src --root-mode upward --extensions .ts,.tsx -d dist/esm --source-maps",
    "build:types": "tsc --emitDeclarationOnly --declaration --declarationMap --declarationDir dist/types",
    "lint": "concurrently yarn:lint:*",
    "lint:src": "eslint src --ext .ts,.tsx --config ../../.eslintrc",
    "lint:types": "tsc --noEmit",
    "prebuild": "rimraf dist",
    "start": "nodemon --watch src --exec yarn build -e ts,tsx",
    "test": "jest --env=jsdom --passWithNoTests",
    "test:cov": "yarn test --coverage",
    "version": "yarn build"
  },
  "sideEffects": false,
  "types": "dist/types/index.d.ts",
  "version": "1.0.0-next.2251"
}
```

**Comment by with-heart** [comment]
Could you create a basic CodeSandbox reproduction for me? I've not used `parcel` before so I'm not sure how to set that up. It's probably not `parcel`-specific, but might as well have it work identical to your situation.

**Comment by lebowski7** [comment]
Hi @with-heart this issue was solved with next release. Thanks for your help. Now I'm facing other build issue connected to chakra, but it's not related to this accordion thing, so it can be closed. Thanks

**Comment by with-heart** [comment]
@lebowski7 Glad to hear it! I'm not sure what happened exactly, but I'm guessing somehow the change wasn't published yet or `node_modules` had an older version in it than you thought it did.

Feel free to make a new issue for the build problem!

**Pull request merged**
