### PR TITLE
chore: refactor motion custom

### PR DESCRIPTION
**Pull request by shunkakinoki**
hi @chakra-ui
Thanks for the awesome project!!!
The error was breaking `@chakra-ui/cli` so updated the command to the non deprecated version

### CODE REVIEW

**Comment by shunkakinoki** [comment]
Closes #3459

**Review by simonzhow — APPROVED** [review]

**Comment by with-heart** [comment]
I'm not sure how I feel about this. It's potentially a breaking change for us to require that consuming projects upgrade `framer-motion` for what amounts to a `console.warn` message.

The issue in particular with `@chakra-ui/cli` is here: https://github.com/chakra-ui/chakra-ui/blob/0830ddcf0989700f9c8e23956726f22247de7ded/tooling/cli/src/command/tokens/index.ts#L28-L30

`console.warn` is reported to `stderr`, which means the deprecation warning is causing `@chakra-ui/cli` to throw this as an error.

I think we're be better off resolving the issue inside `@chakra-ui/cli` as a `console.warn` shouldn't justify forcing an upgrade of `framer-motion`.

**Comment by cloud-walker** [comment]
framer-motion is not supporting the .custom version anymore

**Comment by with-heart** [comment]
I'm going to close this as we can't proceed with these changes. In order to **force** users to upgrade a dependency, we'd need to publish a new `major` version (`@chakra-ui/react@2.0.0`) and I believe we can make some changes that will allow us to silence these issues without **requiring** dependency upgrades.

For now, #3623 adds support for `framer-motion` v4, so you'll be able to upgrade to the latest to silence these once that is merged.

**Comment by with-heart** [comment]
Thank you for the effort though @shunkakinoki!

**Pull request closed without merging**
