### PR TITLE
feat(docs): use preact

### PR DESCRIPTION
**Pull request by ljosberinn**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

The docs will now use Preact.

With React:
image

With Preact:
image

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

React Devtools in won't work in prod anymore sadly.

### CODE REVIEW

**Comment by ljosberinn** [comment]
would be nice if whoever reviews this could throughly go through the docs and check whether all pages/examples still work, just to be sure

**Comment by navin-moorthy** [comment]
I checked most of the pages, here is my update

- Something weird with `react-live` - live aria - https://chakra-ui-git-feat-docs-preact.chakra-ui.vercel.app/docs/migration#6-update-theme-breakpoints & some variation is fonts used there.
- Components using popover is not navigable `Popover, Menu & Tooltip` - Check all the overlay elements.

**Comment by ljosberinn** [comment]
Thank you - looks like `react-live` + preact + popper are somehow incompatible 🤔 looks like some infinite render loop that doesn't throw an error; those tabs become unresponsive. 
The `Menu` itself works with preact [here](http://personal-react-boilerplate.now.sh/)

image

I'll check later on

**Comment by navin-moorthy** [comment]
Exactly, they became unresponsive, so I couldn't understand why this is happening.

**Comment by segunadebayo** [comment]
Let's skip adding Preact for now considering we haven't given preact much considering when building the components.

We can do this in the future.

Thank you @ljosberinn

**Comment by ljosberinn** [comment]
Yeah it's alright, I'll eventually find out the issue anyways when using the components in my repo. If there are any, tbh I think the incompatibility simply stems from react-live here.

**Pull request closed without merging**
