### PR TITLE
feat: embedded getting started video in docs

### PR DESCRIPTION
**Pull request by lazarnikolov94**
## 📝 Description

Embedding the YouTube video "Getting Started with Chakra UI" in the docs

### CODE REVIEW

**Comment by TimKolberger** [comment]
Nice work with the getting started video @lazarnikolov94! ✨ 

I think that it is a good idea to link to this video, but not as the first thing on the getting started page.
In the getting started section at `Next.js` seems like the best fit imo. 
What do you think?

**Comment by lazarnikolov94** [comment]
> Nice work with the getting started video @lazarnikolov94! ✨
> 
> I think that it is a good idea to link to this video, but not as the first thing on the getting started page.
> In the getting started section at `Next.js` seems like the best fit imo.
> What do you think?

It does make sense. I can move it down.

**Comment by lazarnikolov94** [comment]
> > Nice work with the getting started video @lazarnikolov94! ✨
> > I think that it is a good idea to link to this video, but not as the first thing on the getting started page.
> > In the getting started section at `Next.js` seems like the best fit imo.
> > What do you think?
> 
> It does make sense. I can move it down.

You can check it out now @TimKolberger

**Review by TimKolberger — APPROVED** [review]
Looks good to me ✨

**Pull request merged**
