### PR TITLE
docs: Update drawer.mdx

### PR DESCRIPTION
**Pull request by benyou1969**
When full drawer is opened Instead of refresh the page you can press escape to exist

### CODE REVIEW

**Comment by jmiazga** [comment]
Thanks for the PR @benyou1969. Can you update your commit message to follow the required conventions?

https://github.com/chakra-ui/chakra-ui/blob/develop/CONTRIBUTING.md#commit-convention

**Comment by benyou1969** [comment]
Done

**Comment by jmiazga** [comment]
@benyou1969 Thanks for updating the PR title, but you also need to update the commit message to get the Semantic PR check to pass. Let me know if you need any help doing that.

**Comment by benyou1969** [comment]
@jmiazga Thank you for you time. it was my bad i didn't read the contribution section.

**Comment by jmiazga** [comment]
@allcontributors please add @benyou1969 for docs

**Pull request merged**
