### PR TITLE
[WIP]: Improve `orientation` prop support

### LINKED ISSUE #1187: [Tabs] Improve `orientation` prop support
The `Tabs` component technically supports the `orientation` prop (values of `vertical` or `horizontal`), but the effect it has is to switch between `keyDown` handlers for `ArrowUp`+`ArrowDown` or `ArrowLeft`+`ArrowRight` and to alter the `aria-orientation` prop. The default `theme` provides no visual support for the `vertical` orientation, and the `orientation` prop is entirely undocumented.

- [ ] Add `theme` support for `vertical` tabs
- [ ] Document the `orientation` prop

### PR DESCRIPTION
**Pull request by rockchalkwushock**
Closes #1187

@segunadebayo @with-heart 

This is still very much a work in progress.

1. I'm confused about how `orientation` gets addressed within the `theme` as we merge `Tabs` into the default theme.
2. Still needs to have some tests written to verify toggling between the `orientations` gives the desired results.

### CODE REVIEW

**Comment by segunadebayo** [comment]
@rockchalkwushock, kindly change the base branch to develop.

**Comment by with-heart** [comment]
I wonder if there's a way to reset the `changeset-bot` when a PR is updated, like how `lgtm-com` was able to see that the base branch changed and updated its message. I'll look into that, or open an issue in the `changesets` repo if that functionality doesn't exist.

**Comment by with-heart** [comment]
> 1. I'm confused about how `orientation` gets addressed within the `theme` as we merge `Tabs` into the default theme.

Hmm, could expand on this? I'm not sure what you're confused by, so I'm not sure how to help you understand that better.

**Comment by rockchalkwushock** [comment]
@with-heart I apologize for the delay in getting back to you. I had no time to be at the keyboard this weekend. Perhaps I am just not seeing it but in looking at the data structure for the `theme` their is a `components` object that we are spreading the default styles for each component in the library. What I wasn't finding was how `orientation` fits into the component-level data structure.

```ts
// @chakra-ui/theme

const theme = {
  ...foundations,
  components,
  styles,
  config,
}

// @chakra-ui/tabs

// All of the below seem to be the case for all components but `orientation` is not used by all components.
// Is adding it to this object okay or does it need to be spread in somewhere else?
// I don't see a component level theme typing, that's where I am getting a little confused.

const tabs = {
  register,
  defaultProps,
  baseStyles,
  sizes,
  variants,
}
```

**Comment by segunadebayo** [comment]
Thank you for this PR @rockchalkwushock. I just pushed an update taking ideas for this PR, and added some other style updates as well.

**Pull request closed without merging**
